// SPDX-License-Identifier: PHP-3.01

/*
 * Target-neutral instruction-selection snippets for TPDE EncodeGen. The
 * checked-in x86-64 and arm64 headers are generated by regenerate.sh.
 */

typedef unsigned long long zend_native_u64;
typedef long long zend_native_i64;

zend_native_u64 zend_native_add_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left + right;
}

zend_native_u64 zend_native_sub_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left - right;
}

zend_native_u64 zend_native_mul_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left * right;
}

zend_native_u64 zend_native_or_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left | right;
}

zend_native_u64 zend_native_and_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left & right;
}

zend_native_u64 zend_native_xor_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left ^ right;
}

zend_native_u64 zend_native_eq_u64(
	zend_native_u64 left, zend_native_u64 right)
{
	return left == right;
}

zend_native_u64 zend_native_lt_i64(
	zend_native_i64 left, zend_native_i64 right)
{
	return left < right;
}

zend_native_u64 zend_native_le_i64(
	zend_native_i64 left, zend_native_i64 right)
{
	return left <= right;
}

double zend_native_add_f64(double left, double right)
{
	return left + right;
}

double zend_native_sub_f64(double left, double right)
{
	return left - right;
}

double zend_native_mul_f64(double left, double right)
{
	return left * right;
}

zend_native_u64 zend_native_load_u64(const zend_native_u64 *address)
{
	return *address;
}

void zend_native_store_u64(
	zend_native_u64 *address, zend_native_u64 value)
{
	*address = value;
}
