#!/usr/bin/env python3
"""Generate a GNU ld section-ordering file for the hot runtime functions.

The input is one or more callgrind profiles of warm requests and the binary
they were taken from (built with -ffunction-sections).  Functions are
clustered with the C3 heuristic (hfsort): the hottest function is appended to
the cluster of its most frequent caller while the cluster stays within one
page, and clusters are emitted by descending sample density.  The output is a
linker-script fragment for ld --section-ordering-file (binutils 2.43+).

Usage:
  function-order.py --binary sapi/fpm/php-fpm --output FILE CALLGRIND...
"""

import argparse
import collections
import re
import subprocess
import sys

PAGE_SIZE = 4096


def read_profile(path, self_cost, edges):
    names = {}

    def name(token):
        match = re.match(r'\((\d+)\)(?: (.*))?', token)
        if match is None:
            return token.split("'")[0]
        if match.group(2):
            names[match.group(1)] = match.group(2)
        return names.get(match.group(1), '?').split("'")[0]

    function = None
    callee = None
    call_line = False
    with open(path, errors='replace') as profile:
        for line in profile:
            if line.startswith('fn='):
                function = name(line[3:].strip())
                call_line = False
            elif line.startswith('cfn='):
                callee = name(line[4:].strip())
            elif line.startswith('calls='):
                # The cost line after calls= is inclusive cost of the call.
                call_line = True
                edges[(function, callee)] += int(line.split()[0][6:])
            elif line[:1] in '0123456789+-*':
                if call_line:
                    call_line = False
                    continue
                fields = line.split()
                if len(fields) >= 2 and function is not None:
                    try:
                        self_cost[function] += int(fields[-1])
                    except ValueError:
                        pass


def function_sizes(binary):
    sizes = {}
    listing = subprocess.run(['nm', '-S', binary], check=True,
        capture_output=True, text=True).stdout
    for line in listing.splitlines():
        fields = line.split()
        if len(fields) == 4 and fields[2] in ('t', 'T'):
            sizes[fields[3]] = int(fields[1], 16)
    return sizes


def main():
    parser = argparse.ArgumentParser(description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--binary', required=True)
    parser.add_argument('--output', required=True)
    parser.add_argument('profiles', nargs='+')
    args = parser.parse_args()

    self_cost = collections.Counter()
    edges = collections.Counter()
    for profile in args.profiles:
        read_profile(profile, self_cost, edges)
    sizes = function_sizes(args.binary)

    hot = [function for function, cost in self_cost.most_common()
        if cost > 0 and function in sizes]
    hot_set = set(hot)
    callers = collections.defaultdict(collections.Counter)
    for (caller, callee), count in edges.items():
        if caller in hot_set and callee in hot_set and caller != callee:
            callers[callee][caller] += count

    clusters = {function: [function] for function in hot}
    owner = {function: function for function in hot}
    cluster_size = {function: sizes[function] for function in hot}
    cluster_cost = {function: self_cost[function] for function in hot}
    for function in hot:
        if not callers[function]:
            continue
        caller = callers[function].most_common(1)[0][0]
        target = owner[caller]
        source = owner[function]
        if target == source \
                or cluster_size[target] + cluster_size[source] > PAGE_SIZE:
            continue
        clusters[target].extend(clusters[source])
        for member in clusters[source]:
            owner[member] = target
        cluster_size[target] += cluster_size[source]
        cluster_cost[target] += cluster_cost[source]
        del clusters[source]

    order = sorted(clusters,
        key=lambda cluster: -cluster_cost[cluster] / max(cluster_size[cluster], 1))
    with open(args.output, 'w') as output:
        output.write('/* Generated by scripts/native/layout/function-order.py. */\n')
        output.write('.text : {\n')
        for cluster in order:
            for function in clusters[cluster]:
                output.write(f'  *(.text.{function} .text.hot.{function})\n')
        output.write('}\n')
    print(f'{len(hot)} functions in {len(clusters)} clusters, '
        f'{sum(sizes[function] for function in hot)} bytes', file=sys.stderr)


if __name__ == '__main__':
    main()
