// SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception AND CC0-1.0

// NOTE: This file is autogenerated by tpde-encodegen. Please DO NOT edit this file
// as all changes will be overwritten once the file is generated again.
// NOTE: Some parts of this file are subject to the default license of TPDE
// and only the autogenerated code falls under the CC0-1.0 license

// SPDX-SnippetBegin
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#pragma once

#include <optional>
#include <variant>

#include "tpde/base.hpp"
#include "tpde/x64/CompilerX64.hpp"

// Helper macros for assembling in the compiler
#if defined(ASMD)
    #error Got definition for ASM macros from somewhere else. Maybe you included compilers for multiple architectures?
#endif

#define ASMD(...) ASMC(this->derived(), __VA_ARGS__)

namespace tpde_encodegen {

using namespace tpde;

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          typename BaseTy,
          typename Config>
struct EncodeCompiler {
    using CompilerX64  = tpde::x64::CompilerX64<Adaptor, Derived, BaseTy, Config>;
    using ScratchReg   = typename CompilerX64::ScratchReg;
    using AsmReg       = typename CompilerX64::AsmReg;
    using ValuePartRef = typename CompilerX64::ValuePartRef;
    using ValuePart = typename CompilerX64::ValuePart;
    using GenericValuePart = typename CompilerX64::GenericValuePart;

    [[nodiscard]] static std::optional<i32> encodeable_as_imm32_sext(GenericValuePart &gv);
    [[nodiscard]] static std::optional<FeMem> encodeable_as_mem(GenericValuePart &gv, unsigned align);
    [[nodiscard]] static std::optional<FeMem> encodeable_with(GenericValuePart &gv, FeMem other, bool addr32 = false);
    void          try_salvage_or_materialize(GenericValuePart &gv,
                                             ScratchReg     &dst_scratch,
                                             u8              bank,
                                             u32             size);
    void          try_salvage_or_materialize(GenericValuePart &gv,
                                             ValuePart      &dst_scratch,
                                             u8              bank,
                                             u32             size);

    CompilerX64 *derived() {
        return static_cast<CompilerX64 *>(static_cast<Derived *>(this));
    }

    const CompilerX64 *derived() const {
        return static_cast<const CompilerX64 *>(
            static_cast<const Derived *>(this));
    }

    static bool reg_needs_avx512(AsmReg reg) {
        if (reg.id() > AsmReg::XMM15) {
            return true;
        }
        return false;
    }

    [[nodiscard]] bool has_avx() const {
        return derived()->has_cpu_feats(CompilerX64::CPU_AVX);
    }

    [[nodiscard]] static bool disp_add_encodeable(int32_t disp,
                                                  int32_t add) {
        const auto tmp = static_cast<int64_t>(disp) + add;
        return (static_cast<int64_t>(static_cast<int32_t>(tmp)) == tmp);
    }

    struct FixedRegBackup {
        ScratchReg  scratch;
        ValLocalIdx local_idx;
        u32         part;
        u32         lock_count;
    };

    void scratch_alloc_specific(AsmReg                              reg,
                                ScratchReg                         &scratch,
                                std::initializer_list<GenericValuePart *> operands,
                                FixedRegBackup &backup_reg);

    void scratch_check_fixed_backup(ScratchReg     &scratch,
                                    FixedRegBackup &backup_reg,
                                    bool            is_ret_reg);

    void reset() {
        symbols.fill({});
    }

// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0
// clang-format off

  bool encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_add_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_sub_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_mul_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_or_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_and_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_xor_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_eq_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_lt_i64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_le_i64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_add_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_sub_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_mul_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_load_u64(std::move(param_0), result_0); }
  bool encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_load_u32(std::move(param_0), result_0); }
  bool encode_zend_native_store_u64(GenericValuePart &&param_0, GenericValuePart &&param_1);
  bool encode_zend_native_property_slot(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_property_slot(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_property_slot(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_zval_copy(GenericValuePart &&param_0, ValuePart &result_0, ValuePart &result_1);
  bool encode_zend_native_zval_copy(GenericValuePart &&param_0, ValuePart &&result_0, ValuePart &&result_1) {  return encode_zend_native_zval_copy(std::move(param_0), result_0, result_1); }
  bool encode_zend_native_zval_is_true_type(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_zval_is_true_type(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_zval_is_true_type(std::move(param_0), result_0); }
  bool encode_zend_native_load_f64(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_load_f64(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_load_f64(std::move(param_0), result_0); }


    std::array<SymRef, 0> symbols;

};
// SPDX-SnippetEnd



// SPDX-SnippetBegin
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// clang-format on
template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<i32> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_as_imm32_sext(GenericValuePart &gv) {
    if (!gv.is_imm()) {
        return std::nullopt;
    }

    const u64 imm = gv.imm64();
    if (gv.imm_size() <= 4 || static_cast<i64>(static_cast<i32>(imm)) == static_cast<i64>(imm)) {
        // always encodeable
        return static_cast<i32>(imm);
    }

    return std::nullopt;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<FeMem> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_as_mem(GenericValuePart &gv, unsigned align) {
    if (!std::holds_alternative<ValuePartRef>(gv.state)) {
        return std::nullopt;
    }
    const ValuePartRef &vpr = std::get<ValuePartRef>(gv.state);

    if (!vpr.has_assignment()) {
        return std::nullopt;
    }

    const auto ap = vpr.assignment();
    if (ap.register_valid() || ap.variable_ref())
        return std::nullopt;
    if (ap.frame_off() & (align - 1))
        return std::nullopt;
    return FE_MEM(FE_BP, 0, FE_NOREG, ap.frame_off());
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<FeMem> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_with(GenericValuePart &gv, FeMem other, bool addr32) {
    const auto disp_encodeable = [addr32](u64 a, u64 b) -> std::optional<i32> {
        auto sum = static_cast<i32>(a + b);
        if (addr32 || static_cast<i64>(sum) == static_cast<i64>(a + b))
            return sum;
        return std::nullopt;
    };
    const auto is_noreg = [](FeRegGP gp) {
        return gp.idx == FE_NOREG.idx;
    };

    if (gv.is_imm()) {
        if (auto disp = disp_encodeable(gv.imm64(), other.off))
            return FE_MEM(other.base, other.scale, other.idx, *disp);
        return std::nullopt;
    }
    if (const auto *reg = std::get_if<ScratchReg>(&gv.state)) {
        if (is_noreg(other.base))
            return FE_MEM(reg->cur_reg(), other.scale, other.idx, other.off);
        if (is_noreg(other.idx))
            return FE_MEM(other.base, 1, reg->cur_reg(), other.off);
        return std::nullopt;
    }
    if (const auto *expr = std::get_if<typename GenericValuePart::Expr>(&gv.state)) {
        // TODO: check completeness
        auto disp = disp_encodeable(expr->disp, other.off);
        if (!disp)
            return std::nullopt;
        if (!expr->has_index()) {
            if (!expr->has_base())
                return FE_MEM(other.base, other.scale, other.idx, *disp);
            if (is_noreg(other.base))
                return FE_MEM(expr->base_reg(), other.scale, other.idx, *disp);
            if (is_noreg(other.idx))
                return FE_MEM(other.base, 1, expr->base_reg(), *disp);
            return std::nullopt;
        }
        if (expr->scale != 1 && expr->scale != 2 && expr->scale != 4 && expr->scale != 8)
            return std::nullopt;
        auto scale = static_cast<u8>(expr->scale);
        if (!is_noreg(other.idx))
            return std::nullopt;
        if (!expr->has_base())
            return FE_MEM(other.base, scale, expr->index_reg(), *disp);
        if (is_noreg(other.base) && expr->has_base())
            return FE_MEM(expr->base_reg(), scale, expr->index_reg(), *disp);
        return std::nullopt;
    }
    // TODO: ValuePartRef?
    return std::nullopt;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    try_salvage_or_materialize(GenericValuePart &gv,
                               ScratchReg     &dst_scratch,
                               u8              bank,
                               u32             size) {
    AsmReg reg = derived()->gval_as_reg_reuse(gv, dst_scratch);
    if (!dst_scratch.has_reg()) {
        dst_scratch.alloc(RegBank(bank));
    }
    if (dst_scratch.cur_reg() != reg) {
        derived()->mov(dst_scratch.cur_reg(), reg, size);
    }
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    try_salvage_or_materialize(GenericValuePart &gv,
                               ValuePart      &dst_scratch,
                               u8              ,
                               u32             size) {
    AsmReg reg = derived()->gval_as_reg_reuse(gv, dst_scratch);
    if (!dst_scratch.has_reg()) {
        dst_scratch.alloc_reg(derived());
    }
    if (dst_scratch.cur_reg() != reg) {
        derived()->mov(dst_scratch.cur_reg(), reg, size);
    }
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::scratch_alloc_specific(
    AsmReg                              reg,
    ScratchReg                         &scratch,
    std::initializer_list<GenericValuePart *> operands,
    FixedRegBackup                     &backup_reg) {
    if (!derived()->register_file.is_fixed(reg)) [[likely]] {
        scratch.alloc_specific(reg);
        return;
    }

    const auto bank = derived()->register_file.reg_bank(reg);
    if (bank != Config::GP_BANK) {
        // TODO(ts): need to know the size
        TPDE_FATAL("fixed non-gp regs not supported");
    }

    const auto alloc_backup = [this, &backup_reg, &scratch, reg, bank]() {
        const auto bak_reg    = backup_reg.scratch.alloc(bank);
        auto      &reg_file   = derived()->register_file;
        auto      &assignment = reg_file.assignments[reg.id()];
        backup_reg.local_idx  = assignment.local_idx;
        backup_reg.part       = assignment.part;
        backup_reg.lock_count = reg_file.lock_counts[reg.id()];

        assignment.local_idx  = CompilerX64::INVALID_VAL_LOCAL_IDX;
        assignment.part       = 0;
        reg_file.lock_counts[reg.id()] = 0;

        assert(!scratch.has_reg());
        scratch.force_set_reg(reg);

        ASMD(MOV64rr, bak_reg, reg);
    };

    // check if one of the operands holds the fixed register
    for (auto *op_ptr : operands) {
        auto &op = op_ptr->state;
        if (std::holds_alternative<ScratchReg>(op)) {
            auto &op_scratch = std::get<ScratchReg>(op);
            if (op_scratch.cur_reg() == reg) {
                scratch = std::move(op_scratch);
                op_scratch.alloc(bank);
                ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                return;
            }
            continue;
        }

        if (std::holds_alternative<ValuePartRef>(op)) {
            auto &op_ref = std::get<ValuePartRef>(op);
            if (op_ref.has_assignment()) {
                assert(!op_ref.has_reg());
                const auto ap = op_ref.assignment();
                if (ap.register_valid()) {
                    assert(ap.get_reg() != reg);
                }
            } else if (op_ref.has_reg() && op_ref.cur_reg() == reg) {
                if (op_ref.can_salvage()) {
                    // owned temporary: move elsewhere
                    scratch.alloc_specific(op_ref.salvage());
                    op_ref.alloc_reg();
                    ASMD(MOV64rr, op_ref.cur_reg(), reg);
                } else {
                    // unowned temporary: use backup
                    alloc_backup();
                    *op_ptr = typename GenericValuePart::Expr(backup_reg.scratch.cur_reg());
                }
                return;
            }
            continue;
        }

        if (std::holds_alternative<typename GenericValuePart::Expr>(op)) {
            auto &expr = std::get<typename GenericValuePart::Expr>(op);
            if (expr.base_reg() == reg) {
                if (std::holds_alternative<ScratchReg>(expr.base)) {
                    auto &op_scratch = std::get<ScratchReg>(expr.base);
                    scratch          = std::move(op_scratch);
                    op_scratch.alloc(bank);
                    ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                } else {
                    alloc_backup();
                    expr.base = backup_reg.scratch.cur_reg();
                }
                return;
            }
            if (expr.scale != 0 && expr.index_reg() == reg) {
                if (std::holds_alternative<ScratchReg>(expr.index)) {
                    auto &op_scratch = std::get<ScratchReg>(expr.index);
                    scratch          = std::move(op_scratch);
                    op_scratch.alloc(bank);
                    ASMD(MOV64rr, op_scratch.cur_reg(), reg);
                } else {
                    alloc_backup();
                    expr.index = backup_reg.scratch.cur_reg();
                }
                return;
            }
            continue;
        }
    }

    // otherwise temporarily store it somewhere else
    alloc_backup();
    return;
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    scratch_check_fixed_backup(ScratchReg     &scratch,
                               FixedRegBackup &backup_reg,
                               const bool      is_ret_reg) {
    if (!backup_reg.scratch.has_reg()) [[likely]] {
        return;
    }

    assert(scratch.has_reg());
    auto &reg_file        = derived()->register_file;
    auto &assignment      = reg_file.assignments[scratch.cur_reg().id()];
    assignment.local_idx  = backup_reg.local_idx;
    assignment.part       = backup_reg.part;
    reg_file.lock_counts[scratch.cur_reg().id()] = backup_reg.lock_count;

    assert(reg_file.reg_bank(scratch.cur_reg()) == Config::GP_BANK);
    if (is_ret_reg) {
        // TODO(ts): allocate another scratch? Though at this point the scratch
        // regs have not been released yet so we might need to spill...

        // need to switch around backup and reg so it can be returned as a
        // ScratchReg
        ASMD(XCHG64rr, scratch.cur_reg(), backup_reg.scratch.cur_reg());
        scratch.force_set_reg(backup_reg.scratch.cur_reg());
        backup_reg.scratch.force_set_reg(AsmReg::make_invalid());
    } else {
        ASMD(MOV64rr, scratch.cur_reg(), backup_reg.scratch.cur_reg());

        scratch.force_set_reg(AsmReg::make_invalid());
        backup_reg.scratch.reset();
    }
}

// clang-format off
// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_add_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   renamable $rax = LEA64r killed renamable $rdi, 1, killed renamable $rsi, 0, $noreg
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_add_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // renamable $rax = LEA64r killed renamable $rdi, 1, killed renamable $rsi, 0, $noreg
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 1, FE_AX, 0), false);
    if (cond0) {
        AsmReg op3 = derived()->gval_as_reg_reuse(param_1, scratch_ax);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(LEA64rm, scratch_ax.cur_reg(), FE_MEM((*cond0).base, (*cond0).scale, op3, (*cond0).off));
        break;
    }
    }
    {
    auto cond1 = encodeable_with(param_1, FE_MEM(FE_AX, 0, FE_NOREG, 0), false);
    if (cond1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_ax);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(LEA64rm, scratch_ax.cur_reg(), FE_MEM(op1, (*cond1).scale, (*cond1).idx, (*cond1).off));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_ax);
        AsmReg op3 = derived()->gval_as_reg_reuse(param_1, scratch_ax);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(LEA64rm, scratch_ax.cur_reg(), FE_MEM(op1, 1, op3, 0));
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_sub_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   $rax = MOV64rr killed $rdi
    //   renamable $rax = SUB64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_sub_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // $rax = MOV64rr killed $rdi


    // renamable $rax = SUB64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(SUB64ri, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(SUB64rm, scratch_ax.cur_reg(), (*cond1));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SUB64rr, scratch_ax.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_mul_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   $rax = MOV64rr killed $rdi
    //   renamable $rax = IMUL64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_mul_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // $rax = MOV64rr killed $rdi


    // renamable $rax = IMUL64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    do {
    {
    auto cond0 = encodeable_as_mem(param_1, 1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(IMUL64rm, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(IMUL64rr, scratch_ax.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_or_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   $rax = MOV64rr killed $rdi
    //   renamable $rax = OR64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_or_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // $rax = MOV64rr killed $rdi


    // renamable $rax = OR64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(OR64ri, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(OR64rm, scratch_ax.cur_reg(), (*cond1));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(OR64rr, scratch_ax.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_and_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   $rax = MOV64rr killed $rdi
    //   renamable $rax = AND64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_and_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // $rax = MOV64rr killed $rdi


    // renamable $rax = AND64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(AND64ri, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(AND64rm, scratch_ax.cur_reg(), (*cond1));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(AND64rr, scratch_ax.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_xor_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   $rax = MOV64rr killed $rdi
    //   renamable $rax = XOR64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_xor_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // $rax = MOV64rr killed $rdi


    // renamable $rax = XOR64rr killed renamable $rax(tied-def 0), killed renamable $rsi, implicit-def dead $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(XOR64ri, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
    ASMD(XOR64rm, scratch_ax.cur_reg(), (*cond1));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_ax, 0, 8);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(XOR64rr, scratch_ax.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_eq_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    //   renamable $al = SETCCr 4, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_eq_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};
  derived()->set_preserve_flags(true);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst0_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst0_op2);
        break;
    }
    }
    } while (false);


    // CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64ri, op0, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64rm, op0, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
        AsmReg op1 = derived()->gval_as_reg(param_1);
    ASMD(CMP64rr, op0, op1);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $al = SETCCr 4, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    {
    if (1) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(SETZ8r, scratch_ax.cur_reg());
    }
    }


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_lt_i64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    //   renamable $al = SETCCr 12, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_lt_i64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};
  derived()->set_preserve_flags(true);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst0_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst0_op2);
        break;
    }
    }
    } while (false);


    // CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64ri, op0, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64rm, op0, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
        AsmReg op1 = derived()->gval_as_reg(param_1);
    ASMD(CMP64rr, op0, op1);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $al = SETCCr 12, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    {
    if (1) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(SETL8r, scratch_ax.cur_reg());
    }
    }


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_le_i64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    //   renamable $al = SETCCr 14, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_le_i64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};
  derived()->set_preserve_flags(true);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst0_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst0_op2);
        break;
    }
    }
    } while (false);


    // CMP64rr killed renamable $rdi, killed renamable $rsi, implicit-def $eflags
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    if (cond0) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64ri, op0, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_mem(param_1, 1);
    if (cond1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP64rm, op0, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
        AsmReg op1 = derived()->gval_as_reg(param_1);
    ASMD(CMP64rr, op0, op1);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $al = SETCCr 14, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    {
    if (1) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(SETLE8r, scratch_ax.cur_reg());
    }
    }


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_add_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $xmm0, $xmm1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $xmm0, $xmm1
    //   renamable $xmm0 = nofpexcept ADDSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    //   RET64 killed $xmm0
    //
    // # End machine code for function zend_native_add_f64.
    //

    // Mapping xmm0 to param_0
    // Mapping xmm1 to param_1
    ScratchReg scratch_xmm1{derived()};
    ValuePart &scratch_xmm0 = result_0;


    // renamable $xmm0 = nofpexcept ADDSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    do {
    {
    auto cond0 = encodeable_as_mem(param_1, 1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
    ASMD(SSE_ADDSDrm, scratch_xmm0.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SSE_ADDSDrr, scratch_xmm0.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $xmm0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_sub_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $xmm0, $xmm1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $xmm0, $xmm1
    //   renamable $xmm0 = nofpexcept SUBSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    //   RET64 killed $xmm0
    //
    // # End machine code for function zend_native_sub_f64.
    //

    // Mapping xmm0 to param_0
    // Mapping xmm1 to param_1
    ScratchReg scratch_xmm1{derived()};
    ValuePart &scratch_xmm0 = result_0;


    // renamable $xmm0 = nofpexcept SUBSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    do {
    {
    auto cond0 = encodeable_as_mem(param_1, 1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
    ASMD(SSE_SUBSDrm, scratch_xmm0.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SSE_SUBSDrr, scratch_xmm0.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $xmm0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_mul_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $xmm0, $xmm1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $xmm0, $xmm1
    //   renamable $xmm0 = nofpexcept MULSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    //   RET64 killed $xmm0
    //
    // # End machine code for function zend_native_mul_f64.
    //

    // Mapping xmm0 to param_0
    // Mapping xmm1 to param_1
    ScratchReg scratch_xmm1{derived()};
    ValuePart &scratch_xmm0 = result_0;


    // renamable $xmm0 = nofpexcept MULSDrr killed renamable $xmm0(tied-def 0), killed renamable $xmm1, implicit $mxcsr
    do {
    {
    auto cond0 = encodeable_as_mem(param_1, 1);
    if (cond0) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
    ASMD(SSE_MULSDrm, scratch_xmm0.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        try_salvage_or_materialize(param_0, scratch_xmm0, 1, 16);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SSE_MULSDrr, scratch_xmm0.cur_reg(), op2);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64 killed $xmm0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_load_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi
    //
    // bb.0 (%ir-block.1):
    //   liveins: $rdi
    //   renamable $rax = MOV64rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !4)
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_load_u64.
    //

    // Mapping di to param_0
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};


    // renamable $rax = MOV64rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !4)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0), false);
    if (cond0) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_ax);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);
    param_0.reset();


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_load_u32: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi
    //
    // bb.0 (%ir-block.1):
    //   liveins: $rdi
    //   renamable $eax = MOV32rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s32) from %ir.0, !tbaa !8)
    //   RET64 killed $eax
    //
    // # End machine code for function zend_native_load_u32.
    //

    // Mapping di to param_0
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};


    // renamable $eax = MOV32rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s32) from %ir.0, !tbaa !8)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0), false);
    if (cond0) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV32rm, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_ax);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV32rm, scratch_ax.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);
    param_0.reset();


    // RET64 killed $eax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_store_u64(GenericValuePart &&param_0, GenericValuePart &&param_1) {
    // # Machine code for function zend_native_store_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   liveins: $rdi, $rsi
    //   MOV64mr killed renamable $rdi, 1, $noreg, 0, $noreg, killed renamable $rsi :: (store (s64) into %ir.0, !tbaa !4)
    //   RET64
    //
    // # End machine code for function zend_native_store_u64.
    //

    // Mapping di to param_0
    // Mapping si to param_1
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_si{derived()};


    // MOV64mr killed renamable $rdi, 1, $noreg, 0, $noreg, killed renamable $rsi :: (store (s64) into %ir.0, !tbaa !4)
    do {
    {
    auto cond0 = encodeable_as_imm32_sext(param_1);
    auto cond1 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0));
    if (cond0 && cond1) {
    ASMD(MOV64mi, (*cond1), (*cond0));
        break;
    }
    }
    {
    auto cond2 = encodeable_as_imm32_sext(param_1);
    if (cond2) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(MOV64mi, FE_MEM(op0, 0, FE_NOREG, 0), (*cond2));
        break;
    }
    }
    {
    auto cond3 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0), false);
    if (cond3) {
        AsmReg op5 = derived()->gval_as_reg(param_1);
    ASMD(MOV64mr, (*cond3), op5);
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
        AsmReg op5 = derived()->gval_as_reg(param_1);
    ASMD(MOV64mr, FE_MEM(op0, 0, FE_NOREG, 0), op5);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET64
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_property_slot(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_property_slot: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi, $rsi
    //
    // bb.0 (%ir-block.2):
    //   successors: %bb.3(0x40000000), %bb.1(0x40000000); %bb.3(50.00%), %bb.1(50.00%)
    //   liveins: $rdi, $rsi
    //   CMP8mi renamable $rdi, 1, $noreg, 8, $noreg, 8, implicit-def $eflags :: (load (s8) from %ir.3, align 8, !tbaa !4)
    //   JCC_1 %bb.1, 5, implicit killed $eflags
    //
    // bb.3 (%ir-block.6):
    // ; predecessors: %bb.0
    //   successors: %bb.4(0x30000000), %bb.1(0x50000000); %bb.4(37.50%), %bb.1(62.50%)
    //   liveins: $rdi, $rsi
    //   renamable $rcx = MOV64rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !4)
    //   renamable $rax = MOV64rm renamable $rsi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.1, !tbaa !7)
    //   CMP64rm killed renamable $rax, renamable $rcx, 1, $noreg, 16, $noreg, implicit-def $eflags :: (load (s64) from %ir.9, !tbaa !9)
    //   JCC_1 %bb.1, 5, implicit killed $eflags
    //
    // bb.4 (%ir-block.12):
    // ; predecessors: %bb.3
    //   successors: %bb.5(0x40000000), %bb.1(0x40000000); %bb.5(50.00%), %bb.1(50.00%)
    //   liveins: $rcx, $rsi
    //   renamable $rax = MOV64rm killed renamable $rsi, 1, $noreg, 8, $noreg :: (load (s64) from %ir.13, !tbaa !7)
    //   CMP64ri32 renamable $rax, 16, implicit-def $eflags
    //   JCC_1 %bb.1, 12, implicit killed $eflags
    //
    // bb.5 (%ir-block.16):
    // ; predecessors: %bb.4
    //   successors: %bb.1(0x30000000), %bb.6(0x50000000); %bb.1(37.50%), %bb.6(62.50%)
    //   liveins: $rax, $rcx
    //   $edx = MOVZX32rm8 renamable $rcx, 1, renamable $rax, 8, $noreg :: (load (s8) from %ir.19, align 8, !tbaa !4)
    //   TEST8rr renamable $dl, renamable $dl, implicit-def $eflags
    //   JCC_1 %bb.1, 4, implicit killed $eflags
    //
    // bb.6 (%ir-block.22):
    // ; predecessors: %bb.5
    //   liveins: $dl, $rax, $rcx
    //   renamable $rcx = nuw ADD64rr killed renamable $rcx(tied-def 0), killed renamable $rax, implicit-def dead $eflags
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   CMP8ri killed renamable $dl, 10, implicit-def $eflags
    //   renamable $rax = CMOV64rr killed renamable $rax(tied-def 0), killed renamable $rcx, 5, implicit killed $eflags
    //   RET64 killed $rax
    //
    // bb.1:
    // ; predecessors: %bb.0, %bb.3, %bb.4, %bb.5
    //
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_property_slot.
    //

    // Mapping di to param_0
    // Mapping si to param_1

    // Creating label for convergence point at the end of the function
    tpde::Label ret_converge_label = derived()->text_writer.label_create();
    // Creating labels for blocks that are jump targets
    tpde::Label block3_label = derived()->text_writer.label_create();
    tpde::Label block4_label = derived()->text_writer.label_create();
    tpde::Label block5_label = derived()->text_writer.label_create();
    tpde::Label block6_label = derived()->text_writer.label_create();
    tpde::Label block1_label = derived()->text_writer.label_create();

    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ScratchReg scratch_dx{derived()};
    ScratchReg scratch_si{derived()};
    ScratchReg scratch_cx{derived()};
  derived()->set_preserve_flags(true);


    // CMP8mi renamable $rdi, 1, $noreg, 8, $noreg, 8, implicit-def $eflags :: (load (s8) from %ir.3, align 8, !tbaa !4)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 8), false);
    if (cond0) {
    ASMD(CMP8mi, (*cond0), 8);
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP8mi, FE_MEM(op0, 0, FE_NOREG, 8), 0x8);
        break;
    }
    }
    } while (false);


    // JCC_1 %bb.1, 5, implicit killed $eflags
  // allocate registers used later on in the function
  scratch_ax.cur_reg_or_alloc(derived());
  scratch_cx.alloc(RegBank(0));
  scratch_dx.alloc(RegBank(0));
  try_salvage_or_materialize(param_1, scratch_si, 0, 8);
  try_salvage_or_materialize(param_0, scratch_di, 0, 8);
  // Preparing jump to other block
  derived()->generate_raw_jump(Derived::Jump::jne, block1_label);

  // Start of block 3
  derived()->label_place(block3_label);


    // renamable $rcx = MOV64rm killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !4)
    do {
    {
    if (1) {
        AsmReg op1 = scratch_di.cur_reg();
        // def cx has not been allocated yet
        scratch_cx.alloc(RegBank(0));
    ASMD(MOV64rm, scratch_cx.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);


    // renamable $rax = MOV64rm renamable $rsi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.1, !tbaa !7)
    do {
    {
    if (1) {
        AsmReg op1 = scratch_si.cur_reg();
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);


    // CMP64rm killed renamable $rax, renamable $rcx, 1, $noreg, 16, $noreg, implicit-def $eflags :: (load (s64) from %ir.9, !tbaa !9)
    do {
    {
    if (1) {
        AsmReg op0 = scratch_ax.cur_reg();
        AsmReg op1 = scratch_cx.cur_reg();
    ASMD(CMP64rm, op0, FE_MEM(op1, 0, FE_NOREG, 16));
        break;
    }
    }
    } while (false);


    // JCC_1 %bb.1, 5, implicit killed $eflags
  // Preparing jump to other block
  derived()->generate_raw_jump(Derived::Jump::jne, block1_label);

  // Start of block 4
  derived()->label_place(block4_label);


    // renamable $rax = MOV64rm killed renamable $rsi, 1, $noreg, 8, $noreg :: (load (s64) from %ir.13, !tbaa !7)
    do {
    {
    if (1) {
        AsmReg op1 = scratch_si.cur_reg();
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 8));
        break;
    }
    }
    } while (false);


    // CMP64ri32 renamable $rax, 16, implicit-def $eflags
    {
    if (1) {
        AsmReg op0 = scratch_ax.cur_reg();
    ASMD(CMP64ri, op0, 0x10);
    }
    }


    // JCC_1 %bb.1, 12, implicit killed $eflags
  // Preparing jump to other block
  derived()->generate_raw_jump(Derived::Jump::jl, block1_label);

  // Start of block 5
  derived()->label_place(block5_label);


    // $edx = MOVZX32rm8 renamable $rcx, 1, renamable $rax, 8, $noreg :: (load (s8) from %ir.19, align 8, !tbaa !4)
    do {
    {
    if (1) {
        AsmReg op1 = scratch_cx.cur_reg();
        AsmReg op3 = scratch_ax.cur_reg();
        // def dx has not been allocated yet
        scratch_dx.alloc(RegBank(0));
    ASMD(MOVZXr32m8, scratch_dx.cur_reg(), FE_MEM(op1, 1, op3, 8));
        break;
    }
    }
    } while (false);


    // TEST8rr renamable $dl, renamable $dl, implicit-def $eflags
    do {
    {
    if (1) {
        AsmReg op0 = scratch_dx.cur_reg();
    ASMD(TEST8rr, op0, op0);
        break;
    }
    }
    } while (false);


    // JCC_1 %bb.1, 4, implicit killed $eflags
  // Preparing jump to other block
  derived()->generate_raw_jump(Derived::Jump::je, block1_label);

  // Start of block 6
  derived()->label_place(block6_label);


    // renamable $rcx = nuw ADD64rr killed renamable $rcx(tied-def 0), killed renamable $rax, implicit-def dead $eflags
    do {
    {
    if (1) {
        AsmReg op2 = scratch_ax.cur_reg();
    ASMD(ADD64rr, scratch_cx.cur_reg(), op2);
        break;
    }
    }
    } while (false);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst13_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst13_op2);
        break;
    }
    }
    } while (false);


    // CMP8ri killed renamable $dl, 10, implicit-def $eflags
    {
    if (1) {
        AsmReg op0 = scratch_dx.cur_reg();
    ASMD(CMP8ri, op0, 0xa);
    }
    }


    // renamable $rax = CMOV64rr killed renamable $rax(tied-def 0), killed renamable $rcx, 5, implicit killed $eflags
    {
    if (1) {
        AsmReg op2 = scratch_cx.cur_reg();
    ASMD(CMOVNZ64rr, scratch_ax.cur_reg(), op2);
    }
    }


    // RET64 killed $rax
  derived()->generate_raw_jump(Derived::Jump::jmp, ret_converge_label);
  // Start of block 1
  derived()->label_place(block1_label);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst17_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst17_op2);
        break;
    }
    }
    } while (false);


    // RET64 killed $rax
  derived()->label_place(ret_converge_label);
  if (result_0.has_assignment())
    result_0.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_zval_copy(GenericValuePart &&param_0, ValuePart &result_0, ValuePart &result_1) {
    // # Machine code for function zend_native_zval_copy: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi
    //
    // bb.0 (%ir-block.1):
    //   successors: %bb.2(0x30000000), %bb.1(0x50000000); %bb.2(37.50%), %bb.1(62.50%)
    //   liveins: $rdi
    //   renamable $rax = MOV64rm renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0)
    //   renamable $edx = MOV32rm killed renamable $rdi, 1, $noreg, 8, $noreg, implicit-def $rdx :: (load (s32) from %ir.3, align 8, !tbaa !4)
    //   TEST32ri renamable $edx, 65280, implicit-def $eflags
    //   JCC_1 %bb.2, 4, implicit killed $eflags
    //
    // bb.1 (%ir-block.8):
    // ; predecessors: %bb.0
    //   successors: %bb.2(0x80000000); %bb.2(100.00%)
    //   liveins: $rax, $rdx
    //   ADD32mi renamable $rax, 1, $noreg, 0, $noreg, 1, implicit-def dead $eflags :: (store (s32) into %ir.9, !tbaa !16), (load (s32) from %ir.9, !tbaa !16)
    //
    // bb.2 (%ir-block.12):
    // ; predecessors: %bb.0, %bb.1
    //   liveins: $rax, $rdx
    //   RET64 killed $rax, killed $rdx
    //
    // # End machine code for function zend_native_zval_copy.
    //

    // Mapping di to param_0

    // Creating label for convergence point at the end of the function
    tpde::Label ret_converge_label = derived()->text_writer.label_create();
    // Creating labels for blocks that are jump targets
    tpde::Label block1_label = derived()->text_writer.label_create();
    tpde::Label block2_label = derived()->text_writer.label_create();

    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
    ValuePart &scratch_dx = result_1;
  derived()->set_preserve_flags(true);


    // renamable $rax = MOV64rm renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0), false);
    if (cond0) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(MOV64rm, scratch_ax.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);


    // renamable $edx = MOV32rm killed renamable $rdi, 1, $noreg, 8, $noreg, implicit-def $rdx :: (load (s32) from %ir.3, align 8, !tbaa !4)
    do {
    {
    auto cond1 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 8), false);
    if (cond1) {
        // def dx has not been allocated yet
        scratch_dx.cur_reg_or_alloc(derived());
    ASMD(MOV32rm, scratch_dx.cur_reg(), (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_dx);
        // def dx has not been allocated yet
        scratch_dx.cur_reg_or_alloc(derived());
    ASMD(MOV32rm, scratch_dx.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 8));
        break;
    }
    }
    } while (false);
    param_0.reset();


    // TEST32ri renamable $edx, 65280, implicit-def $eflags
    {
    if (1) {
        AsmReg op0 = scratch_dx.cur_reg();
    ASMD(TEST32ri, op0, 0xff00);
    }
    }


    // JCC_1 %bb.2, 4, implicit killed $eflags
  // allocate registers used later on in the function
  scratch_ax.cur_reg_or_alloc(derived());
  scratch_dx.cur_reg_or_alloc(derived());
  // Preparing jump to other block
  derived()->generate_raw_jump(Derived::Jump::je, block2_label);

  // Start of block 1
  derived()->label_place(block1_label);


    // ADD32mi renamable $rax, 1, $noreg, 0, $noreg, 1, implicit-def dead $eflags :: (store (s32) into %ir.9, !tbaa !16), (load (s32) from %ir.9, !tbaa !16)
    do {
    {
    if (1) {
        AsmReg op0 = scratch_ax.cur_reg();
    ASMD(ADD32mi, FE_MEM(op0, 0, FE_NOREG, 0), 0x1);
        break;
    }
    }
    } while (false);
  // Start of block 2
  derived()->label_place(block2_label);


    // RET64 killed $rax, killed $rdx
  derived()->label_place(ret_converge_label);
  if (result_0.has_assignment())
    result_0.unlock(derived());
  if (result_1.has_assignment())
    result_1.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_zval_is_true_type(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_zval_is_true_type: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi
    //
    // bb.0 (%ir-block.1):
    //   liveins: $rdi
    //   renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    //   CMP8mi killed renamable $rdi, 1, $noreg, 8, $noreg, 3, implicit-def $eflags :: (load (s8) from %ir.2, align 8, !tbaa !4)
    //   renamable $al = SETCCr 4, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    //   RET64 killed $rax
    //
    // # End machine code for function zend_native_zval_is_true_type.
    //

    // Mapping di to param_0
    ValuePart &scratch_ax = result_0;
    ScratchReg scratch_di{derived()};
  derived()->set_preserve_flags(true);


    // renamable $eax = XOR32rr undef $eax(tied-def 0), undef $eax, implicit-def dead $eflags, implicit-def $rax
    do {
    {
    if (1) {
        // undef tied
        // undef allocate scratch
        AsmReg inst0_op2 = scratch_ax.cur_reg_or_alloc(derived());

        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(XOR32rr, scratch_ax.cur_reg(), inst0_op2);
        break;
    }
    }
    } while (false);


    // CMP8mi killed renamable $rdi, 1, $noreg, 8, $noreg, 3, implicit-def $eflags :: (load (s8) from %ir.2, align 8, !tbaa !4)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 8), false);
    if (cond0) {
    ASMD(CMP8mi, (*cond0), 3);
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_0);
    ASMD(CMP8mi, FE_MEM(op0, 0, FE_NOREG, 8), 0x3);
        break;
    }
    }
    } while (false);
    param_0.reset();


    // renamable $al = SETCCr 4, implicit killed $eflags, implicit killed $rax, implicit-def $rax
    {
    if (1) {
        // def ax has not been allocated yet
        scratch_ax.cur_reg_or_alloc(derived());
    ASMD(SETZ8r, scratch_ax.cur_reg());
    }
    }


    // RET64 killed $rax
  if (result_0.has_assignment())
    result_0.unlock(derived());
  derived()->set_preserve_flags(false);
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_load_f64(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_load_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $rdi
    //
    // bb.0 (%ir-block.1):
    //   liveins: $rdi
    //   renamable $xmm0 = MOVSDrm_alt killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !17)
    //   RET64 killed $xmm0
    //
    // # End machine code for function zend_native_load_f64.
    //

    // Mapping di to param_0
    ScratchReg scratch_di{derived()};
    ValuePart &scratch_xmm0 = result_0;


    // renamable $xmm0 = MOVSDrm_alt killed renamable $rdi, 1, $noreg, 0, $noreg :: (load (s64) from %ir.0, !tbaa !17)
    do {
    {
    auto cond0 = encodeable_with(param_0, FE_MEM(FE_NOREG, 0, FE_NOREG, 0), false);
    if (cond0) {
        // def xmm0 has not been allocated yet
        scratch_xmm0.cur_reg_or_alloc(derived());
    ASMD(SSE_MOVSDrm, scratch_xmm0.cur_reg(), (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
        // def xmm0 has not been allocated yet
        scratch_xmm0.cur_reg_or_alloc(derived());
    ASMD(SSE_MOVSDrm, scratch_xmm0.cur_reg(), FE_MEM(op1, 0, FE_NOREG, 0));
        break;
    }
    }
    } while (false);
    param_0.reset();


    // RET64 killed $xmm0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}



} // namespace tpde_encodegen

#undef ASMD
// SPDX-SnippetEnd
