// SPDX-FileCopyrightText: 2025 Contributors to TPDE <https://tpde.org>
//
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception AND CC0-1.0

// NOTE: This file is autogenerated by tpde-encodegen. Please DO NOT edit this file
// as all changes will be overwritten once the file is generated again.
// NOTE: Some parts of this file are subject to the default license of TPDE
// and only the autogenerated code falls under the CC0-1.0 license

// SPDX-SnippetBegin
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#pragma once

#include <variant>

#include "tpde/base.hpp"
#include "tpde/arm64/CompilerA64.hpp"

// Helper macros for assembling in the compiler
#if defined(ASMD)
    #error Got definition for ASM macros from somewhere else. Maybe you included compilers for multiple architectures?
#endif

#define ASMD(...) ASMC(this->derived(), __VA_ARGS__)

namespace tpde_encodegen {

using namespace tpde;

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          typename BaseTy,
          typename Config>
struct EncodeCompiler {
    using CompilerA64  = tpde::a64::CompilerA64<Adaptor, Derived, BaseTy, Config>;
    using ScratchReg   = typename CompilerA64::ScratchReg;
    using AsmReg       = typename CompilerA64::AsmReg;
    using ValuePartRef = typename CompilerA64::ValuePartRef;
    using ValuePart = typename CompilerA64::ValuePart;
    using GenericValuePart = typename CompilerA64::GenericValuePart;

    std::optional<u64> encodeable_as_shiftimm(GenericValuePart &gv, unsigned size) const {
        if (gv.is_imm() && gv.imm_size() <= 8) {
            return gv.imm64() & (size - 1);
        }
        return std::nullopt;
    }
    std::optional<u64> encodeable_as_immarith(GenericValuePart &gv) const {
        if (gv.is_imm() && gv.imm_size() <= 8) {
            u64 val = gv.imm64();
            val     = static_cast<i64>(val) < 0 ? -val : val;
            if ((val & 0xfff) == val || (val & 0xff'f000) == val) {
                return gv.imm64();
            }
        }
        return std::nullopt;
    }
    std::optional<u64> encodeable_as_immlogical(GenericValuePart &gv, bool inv) const {
        if (gv.is_imm()) {
            u64 imm = gv.imm64() ^ (inv ? ~u64{0} : 0);
            if (gv.imm_size() == 8 && de64_ANDxi(DA_GP(0), DA_GP(0), imm))
                return imm;
            if (gv.imm_size() <= 4 && de64_ANDwi(DA_GP(0), DA_GP(0), imm))
                return imm;
        }
        return std::nullopt;
    }
    std::optional<std::pair<AsmReg, u64>> encodeable_with_mem_uoff12(GenericValuePart &gv, u64 off, unsigned shift);

    void   try_salvage_or_materialize(GenericValuePart &gv,
                                             ScratchReg     &dst_scratch,
                                             u8              bank,
                                             u32             size);
    void   try_salvage_or_materialize(GenericValuePart &gv,
                                             ValuePart      &dst_scratch,
                                             u8              bank,
                                             u32             size);

    CompilerA64 *derived() {
        return static_cast<CompilerA64 *>(static_cast<Derived *>(this));
    }

    const CompilerA64 *derived() const {
        return static_cast<const CompilerA64 *>(
            static_cast<const Derived *>(this));
    }

    void reset() {
        symbols.fill({});
    }

// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0
// clang-format off

  bool encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_add_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_sub_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_mul_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_or_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_and_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_xor_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_eq_u64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_lt_i64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_le_i64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_add_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_sub_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0);
  bool encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &&result_0) {  return encode_zend_native_mul_f64(std::move(param_0), std::move(param_1), result_0); }
  bool encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_load_u64(std::move(param_0), result_0); }
  bool encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &result_0);
  bool encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &&result_0) {  return encode_zend_native_load_u32(std::move(param_0), result_0); }
  bool encode_zend_native_store_u64(GenericValuePart &&param_0, GenericValuePart &&param_1);


    std::array<SymRef, 0> symbols;

};
// SPDX-SnippetEnd



// SPDX-SnippetBegin
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
// clang-format on
template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
std::optional<std::pair<typename EncodeCompiler<Adaptor, Derived, BaseTy, Config>::AsmReg, u64>> EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    encodeable_with_mem_uoff12(GenericValuePart &gv, u64 off, unsigned shift) {
    auto *expr = std::get_if<typename GenericValuePart::Expr>(&gv.state);
    if (!expr || !expr->has_base()) {
        return std::nullopt;
    }

    u64 res_off = expr->disp + off;
    if (res_off >= (u64{0x1000} << shift) || (res_off & ((1 << shift) - 1))) {
        return std::nullopt;
    }
    if (res_off == 0 && expr->has_index()) {
        // In this case, try index encoding.
        return std::nullopt;
    }

    if (!expr->has_index()) {
        return std::make_pair(expr->base_reg(), res_off);
    }
    if ((expr->scale & (expr->scale - 1)) != 0) {
        return std::nullopt;
    }

    ScratchReg scratch{derived()};
    AsmReg base_reg = expr->base_reg();
    AsmReg index_reg = expr->index_reg();
    if (std::holds_alternative<ScratchReg>(expr->base)) {
        scratch = std::move(std::get<ScratchReg>(expr->base));
    } else if (std::holds_alternative<ScratchReg>(expr->index)) {
        scratch = std::move(std::get<ScratchReg>(expr->index));
    } else {
        (void)scratch.alloc_gp();
    }
    const auto scale_shift = __builtin_ctzl(expr->scale);
    AsmReg dst = scratch.cur_reg();
    ASMD(ADDx_lsl, dst, base_reg, index_reg, scale_shift);
    if (expr->disp != 0) {
        expr->base = std::move(scratch);
        expr->index = AsmReg::make_invalid();
        expr->scale = 0;
    } else {
        gv.state = std::move(scratch);
    }

    return std::make_pair(dst, res_off);
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    try_salvage_or_materialize(GenericValuePart &gv,
                               ScratchReg     &dst_scratch,
                               u8              bank,
                               u32             size) {
    AsmReg reg = derived()->gval_as_reg_reuse(gv, dst_scratch);
    if (!dst_scratch.has_reg()) {
        dst_scratch.alloc(RegBank(bank));
    }
    if (dst_scratch.cur_reg() != reg) {
        derived()->mov(dst_scratch.cur_reg(), reg, size);
    }
}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
void EncodeCompiler<Adaptor, Derived, BaseTy, Config>::
    try_salvage_or_materialize(GenericValuePart &gv,
                               ValuePart      &dst_scratch,
                               u8              ,
                               u32             size) {
    AsmReg reg = derived()->gval_as_reg_reuse(gv, dst_scratch);
    if (!dst_scratch.has_reg()) {
        dst_scratch.alloc_reg(derived());
    }
    if (dst_scratch.cur_reg() != reg) {
        derived()->mov(dst_scratch.cur_reg(), reg, size);
    }
}

// clang-format off
// SPDX-SnippetEnd
// SPDX-SnippetBegin
// SPDX-License-Identifier: CC0-1.0

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_add_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_add_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $x0 = ADDXrs killed renamable $x1, killed renamable $x0, 0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_add_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $x0 = ADDXrs killed renamable $x1, killed renamable $x0, 0
    do {
    {
    auto cond0 = encodeable_as_immarith(param_0);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ADDxi, scratch_x0.cur_reg(), op1, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_immarith(param_1);
    if (cond1) {
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ADDxi, scratch_x0.cur_reg(), op2, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ADDx_lsl, scratch_x0.cur_reg(), op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_1.reset();
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_sub_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_sub_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $x0 = SUBXrs killed renamable $x0, killed renamable $x1, 0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_sub_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $x0 = SUBXrs killed renamable $x0, killed renamable $x1, 0
    do {
    {
    auto cond0 = encodeable_as_immarith(param_1);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(SUBxi, scratch_x0.cur_reg(), op1, (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(SUBx_lsl, scratch_x0.cur_reg(), op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_mul_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_mul_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   renamable $x0 = MADDXrrr killed renamable $x1, killed renamable $x0, $xzr
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_mul_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // renamable $x0 = MADDXrrr killed renamable $x1, killed renamable $x0, $xzr
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(MADDx, scratch_x0.cur_reg(), op1, op2, DA_ZR);
    }
    }
    param_1.reset();
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_or_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_or_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $x0 = ORRXrs killed renamable $x1, killed renamable $x0, 0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_or_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $x0 = ORRXrs killed renamable $x1, killed renamable $x0, 0
    do {
    {
    auto cond0 = encodeable_as_immlogical(param_0, false);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ORRxi, scratch_x0.cur_reg(), op1, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_immlogical(param_1, false);
    if (cond1) {
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ORRxi, scratch_x0.cur_reg(), op2, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ORRx_lsl, scratch_x0.cur_reg(), op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_1.reset();
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_and_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_and_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $x0 = ANDXrs killed renamable $x1, killed renamable $x0, 0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_and_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $x0 = ANDXrs killed renamable $x1, killed renamable $x0, 0
    do {
    {
    auto cond0 = encodeable_as_immlogical(param_0, false);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ANDxi, scratch_x0.cur_reg(), op1, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_immlogical(param_1, false);
    if (cond1) {
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ANDxi, scratch_x0.cur_reg(), op2, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(ANDx_lsl, scratch_x0.cur_reg(), op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_1.reset();
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_xor_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_xor_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $x0 = EORXrs killed renamable $x1, killed renamable $x0, 0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_xor_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $x0 = EORXrs killed renamable $x1, killed renamable $x0, 0
    do {
    {
    auto cond0 = encodeable_as_immlogical(param_0, false);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(EORxi, scratch_x0.cur_reg(), op1, (*cond0));
        break;
    }
    }
    {
    auto cond1 = encodeable_as_immlogical(param_1, false);
    if (cond1) {
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(EORxi, scratch_x0.cur_reg(), op2, (*cond1));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_1, scratch_x0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(EORx_lsl, scratch_x0.cur_reg(), op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_1.reset();
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_eq_u64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_eq_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    //   renamable $w0 = CSINCWr $wzr, $wzr, 1, implicit killed $nzcv, implicit-def $x0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_eq_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    do {
    {
    auto cond0 = encodeable_as_immarith(param_1);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
    ASMD(SUBSxi, DA_ZR, op1, (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SUBSx_lsl, DA_ZR, op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $w0 = CSINCWr $wzr, $wzr, 1, implicit killed $nzcv, implicit-def $x0
    {
    if (1) {
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(CSINCw, scratch_x0.cur_reg(), DA_ZR, DA_ZR, DA_NE);
    }
    }


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_lt_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_lt_i64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    //   renamable $w0 = CSINCWr $wzr, $wzr, 10, implicit killed $nzcv, implicit-def $x0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_lt_i64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    do {
    {
    auto cond0 = encodeable_as_immarith(param_1);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
    ASMD(SUBSxi, DA_ZR, op1, (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SUBSx_lsl, DA_ZR, op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $w0 = CSINCWr $wzr, $wzr, 10, implicit killed $nzcv, implicit-def $x0
    {
    if (1) {
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(CSINCw, scratch_x0.cur_reg(), DA_ZR, DA_ZR, DA_GE);
    }
    }


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_le_i64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_le_i64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    //   renamable $w0 = CSINCWr $wzr, $wzr, 12, implicit killed $nzcv, implicit-def $x0
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_le_i64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ValuePart &scratch_x0 = result_0;
    ScratchReg scratch_x1{derived()};


    // $xzr = SUBSXrs killed renamable $x0, killed renamable $x1, 0, implicit-def $nzcv
    do {
    {
    auto cond0 = encodeable_as_immarith(param_1);
    if (cond0) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
    ASMD(SUBSxi, DA_ZR, op1, (*cond0));
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg(param_0);
        AsmReg op2 = derived()->gval_as_reg(param_1);
    ASMD(SUBSx_lsl, DA_ZR, op1, op2, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();
    param_1.reset();


    // renamable $w0 = CSINCWr $wzr, $wzr, 12, implicit killed $nzcv, implicit-def $x0
    {
    if (1) {
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(CSINCw, scratch_x0.cur_reg(), DA_ZR, DA_ZR, DA_GT);
    }
    }


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_add_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_add_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $d0, $d1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $d0, $d1
    //   renamable $d0 = nofpexcept FADDDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    //   RET undef $lr, implicit killed $d0
    //
    // # End machine code for function zend_native_add_f64.
    //

    // Mapping v0 to param_0
    // Mapping v1 to param_1
    ScratchReg scratch_v1{derived()};
    ValuePart &scratch_v0 = result_0;


    // renamable $d0 = nofpexcept FADDDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_v0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_1, scratch_v0);
        // def v0 has not been allocated yet
        scratch_v0.cur_reg_or_alloc(derived());
    ASMD(FADDd, scratch_v0.cur_reg(), op1, op2);
    }
    }
    param_0.reset();
    param_1.reset();


    // RET undef $lr, implicit killed $d0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_sub_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_sub_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $d0, $d1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $d0, $d1
    //   renamable $d0 = nofpexcept FSUBDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    //   RET undef $lr, implicit killed $d0
    //
    // # End machine code for function zend_native_sub_f64.
    //

    // Mapping v0 to param_0
    // Mapping v1 to param_1
    ScratchReg scratch_v1{derived()};
    ValuePart &scratch_v0 = result_0;


    // renamable $d0 = nofpexcept FSUBDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_v0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_1, scratch_v0);
        // def v0 has not been allocated yet
        scratch_v0.cur_reg_or_alloc(derived());
    ASMD(FSUBd, scratch_v0.cur_reg(), op1, op2);
    }
    }
    param_0.reset();
    param_1.reset();


    // RET undef $lr, implicit killed $d0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_mul_f64(GenericValuePart &&param_0, GenericValuePart &&param_1, ValuePart &result_0) {
    // # Machine code for function zend_native_mul_f64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $d0, $d1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $d0, $d1
    //   renamable $d0 = nofpexcept FMULDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    //   RET undef $lr, implicit killed $d0
    //
    // # End machine code for function zend_native_mul_f64.
    //

    // Mapping v0 to param_0
    // Mapping v1 to param_1
    ScratchReg scratch_v1{derived()};
    ValuePart &scratch_v0 = result_0;


    // renamable $d0 = nofpexcept FMULDrr killed renamable $d0, killed renamable $d1, implicit $fpcr
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_v0);
        AsmReg op2 = derived()->gval_as_reg_reuse(param_1, scratch_v0);
        // def v0 has not been allocated yet
        scratch_v0.cur_reg_or_alloc(derived());
    ASMD(FMULd, scratch_v0.cur_reg(), op1, op2);
    }
    }
    param_0.reset();
    param_1.reset();


    // RET undef $lr, implicit killed $d0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_load_u64(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_load_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0
    //
    // bb.0 (%ir-block.1):
    //   liveins: $x0
    //   renamable $x0 = LDRXui killed renamable $x0, 0 :: (load (s64) from %ir.0, !tbaa !8)
    //   RET undef $lr, implicit killed $x0
    //
    // # End machine code for function zend_native_load_u64.
    //

    // Mapping x0 to param_0
    ValuePart &scratch_x0 = result_0;


    // renamable $x0 = LDRXui killed renamable $x0, 0 :: (load (s64) from %ir.0, !tbaa !8)
    do {
    {
    auto cond0 = encodeable_with_mem_uoff12(param_0, 0x0, 3);
    if (cond0) {
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(LDRxu, scratch_x0.cur_reg(), (*cond0).first, (*cond0).second);
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(LDRxu, scratch_x0.cur_reg(), op1, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();


    // RET undef $lr, implicit killed $x0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_load_u32(GenericValuePart &&param_0, ValuePart &result_0) {
    // # Machine code for function zend_native_load_u32: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0
    //
    // bb.0 (%ir-block.1):
    //   liveins: $x0
    //   renamable $w0 = LDRWui killed renamable $x0, 0 :: (load (s32) from %ir.0, !tbaa !4)
    //   RET undef $lr, implicit killed $w0
    //
    // # End machine code for function zend_native_load_u32.
    //

    // Mapping x0 to param_0
    ValuePart &scratch_x0 = result_0;


    // renamable $w0 = LDRWui killed renamable $x0, 0 :: (load (s32) from %ir.0, !tbaa !4)
    do {
    {
    auto cond0 = encodeable_with_mem_uoff12(param_0, 0x0, 2);
    if (cond0) {
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(LDRwu, scratch_x0.cur_reg(), (*cond0).first, (*cond0).second);
        break;
    }
    }
    {
    if (1) {
        AsmReg op1 = derived()->gval_as_reg_reuse(param_0, scratch_x0);
        // def x0 has not been allocated yet
        scratch_x0.cur_reg_or_alloc(derived());
    ASMD(LDRwu, scratch_x0.cur_reg(), op1, 0);
        break;
    }
    }
    } while (false);
    param_0.reset();


    // RET undef $lr, implicit killed $w0
  if (result_0.has_assignment())
    result_0.unlock(derived());
  return true;

}

template <typename Adaptor,
          typename Derived,
          template <typename, typename, typename>
          class BaseTy,
          typename Config>
bool EncodeCompiler<Adaptor, Derived, BaseTy, Config>::encode_zend_native_store_u64(GenericValuePart &&param_0, GenericValuePart &&param_1) {
    // # Machine code for function zend_native_store_u64: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
    // Function Live Ins: $x0, $x1
    //
    // bb.0 (%ir-block.2):
    //   liveins: $x0, $x1
    //   STRXui killed renamable $x1, killed renamable $x0, 0 :: (store (s64) into %ir.0, !tbaa !8)
    //   RET undef $lr
    //
    // # End machine code for function zend_native_store_u64.
    //

    // Mapping x0 to param_0
    // Mapping x1 to param_1
    ScratchReg scratch_x0{derived()};
    ScratchReg scratch_x1{derived()};


    // STRXui killed renamable $x1, killed renamable $x0, 0 :: (store (s64) into %ir.0, !tbaa !8)
    do {
    {
    auto cond0 = encodeable_with_mem_uoff12(param_0, 0x0, 3);
    if (cond0) {
        AsmReg op0 = derived()->gval_as_reg(param_1);
    ASMD(STRxu, op0, (*cond0).first, (*cond0).second);
        break;
    }
    }
    {
    if (1) {
        AsmReg op0 = derived()->gval_as_reg(param_1);
        AsmReg op1 = derived()->gval_as_reg(param_0);
    ASMD(STRxu, op0, op1, 0);
        break;
    }
    }
    } while (false);
    param_1.reset();
    param_0.reset();


    // RET undef $lr
  return true;

}



} // namespace tpde_encodegen

#undef ASMD
// SPDX-SnippetEnd
