#ifndef ZEND_MIR_LOWERING_DIAGNOSTIC_H
#define ZEND_MIR_LOWERING_DIAGNOSTIC_H

typedef enum _zend_mir_lowering_status {
	ZEND_MIR_LOWERING_SUCCESS = 0,
	ZEND_MIR_LOWERING_DEFERRED = 1,
	ZEND_MIR_LOWERING_REJECTED = 2,
	ZEND_MIR_LOWERING_FAILED = 3,
	ZEND_MIR_LOWERING_STATUS_INVALID = -1
} zend_mir_lowering_status;

typedef enum _zend_mir_lowering_diagnostic_code {
	ZEND_MIRL_OK = 0,
	ZEND_MIRL_DEFERRED_OPCODE = 1,
	ZEND_MIRL_MISSING_PROOF = 2,
	ZEND_MIRL_CONTRADICTORY_FACT = 3,
	ZEND_MIRL_DUPLICATE_PROVIDER_CLAIM = 4,
	ZEND_MIRL_UNKNOWN_PROVIDER = 5,
	ZEND_MIRL_INVALID_SOURCE = 6,
	ZEND_MIRL_MUTATION_FAILED = 7,
	ZEND_MIRL_FINALIZE_FAILED = 8,
	ZEND_MIRL_STAGE1_VERIFY_FAILED = 9,
	ZEND_MIRL_STAGE2_VERIFY_FAILED = 10,
	ZEND_MIRL_W04_CONTROL_FLOW_DEFERRED = 11,
	ZEND_MIRL_W05_RUNTIME_EFFECT_DEFERRED = 12,
	ZEND_MIRL_W06_REFERENCE_SEMANTICS_DEFERRED = 13,
	ZEND_MIRL_W04_MALFORMED_CFG = 14,
	ZEND_MIRL_W04_PROTECTED_REGION = 15,
	ZEND_MIRL_W04_IRREDUCIBLE_LOOP = 16,
	ZEND_MIRL_W04_UNSUPPORTED_PHI_PI = 17,
	ZEND_MIRL_W04_BRANCH_PROOF_FAILED = 18,
	ZEND_MIRL_W04_SOURCE_MIR_MAPPING_FAILED = 19,
	ZEND_MIRL_STAGE3_VERIFY_FAILED = 20,
	ZEND_MIRL_W05_MALFORMED_CALL_SEQUENCE = 21,
	ZEND_MIRL_W05_ORPHAN_CALL_FRAGMENT = 22,
	ZEND_MIRL_W05_UNSUPPORTED_TARGET = 23,
	ZEND_MIRL_W05_UNSUPPORTED_ARGUMENT = 24,
	ZEND_MIRL_W05_ARGUMENT_COUNT_MISMATCH = 25,
	ZEND_MIRL_W05_UNSUPPORTED_RESULT = 26,
	ZEND_MIRL_W05_PROTECTED_CALL = 27,
	ZEND_MIRL_W05_CALL_PLAN_FAILED = 28,
	ZEND_MIRL_W05_CALL_VERIFY_FAILED = 29,
	ZEND_MIRL_DIAGNOSTIC_CODE_COUNT = 30,
	ZEND_MIRL_DIAGNOSTIC_CODE_INVALID = -1
} zend_mir_lowering_diagnostic_code;

typedef zend_mir_lowering_diagnostic_code zend_mir_lowering_code;

#define ZEND_MIRL_TOKEN_OK "[MIRL0000]"
#define ZEND_MIRL_TOKEN_DEFERRED_OPCODE "[MIRL0001]"
#define ZEND_MIRL_TOKEN_MISSING_PROOF "[MIRL0002]"
#define ZEND_MIRL_TOKEN_CONTRADICTORY_FACT "[MIRL0003]"
#define ZEND_MIRL_TOKEN_DUPLICATE_PROVIDER_CLAIM "[MIRL0004]"
#define ZEND_MIRL_TOKEN_UNKNOWN_PROVIDER "[MIRL0005]"
#define ZEND_MIRL_TOKEN_INVALID_SOURCE "[MIRL0006]"
#define ZEND_MIRL_TOKEN_MUTATION_FAILED "[MIRL0007]"
#define ZEND_MIRL_TOKEN_FINALIZE_FAILED "[MIRL0008]"
#define ZEND_MIRL_TOKEN_STAGE1_VERIFY_FAILED "[MIRL0009]"
#define ZEND_MIRL_TOKEN_STAGE2_VERIFY_FAILED "[MIRL0010]"
#define ZEND_MIRL_TOKEN_W04_CONTROL_FLOW_DEFERRED "[MIRL0011]"
#define ZEND_MIRL_TOKEN_W05_RUNTIME_EFFECT_DEFERRED "[MIRL0012]"
#define ZEND_MIRL_TOKEN_W06_REFERENCE_SEMANTICS_DEFERRED "[MIRL0013]"
#define ZEND_MIRL_TOKEN_W04_MALFORMED_CFG "[MIRL0014]"
#define ZEND_MIRL_TOKEN_W04_PROTECTED_REGION "[MIRL0015]"
#define ZEND_MIRL_TOKEN_W04_IRREDUCIBLE_LOOP "[MIRL0016]"
#define ZEND_MIRL_TOKEN_W04_UNSUPPORTED_PHI_PI "[MIRL0017]"
#define ZEND_MIRL_TOKEN_W04_BRANCH_PROOF_FAILED "[MIRL0018]"
#define ZEND_MIRL_TOKEN_W04_SOURCE_MIR_MAPPING_FAILED "[MIRL0019]"
#define ZEND_MIRL_TOKEN_STAGE3_VERIFY_FAILED "[MIRL0020]"
#define ZEND_MIRL_TOKEN_W05_MALFORMED_CALL_SEQUENCE "[MIRL0021]"
#define ZEND_MIRL_TOKEN_W05_ORPHAN_CALL_FRAGMENT "[MIRL0022]"
#define ZEND_MIRL_TOKEN_W05_UNSUPPORTED_TARGET "[MIRL0023]"
#define ZEND_MIRL_TOKEN_W05_UNSUPPORTED_ARGUMENT "[MIRL0024]"
#define ZEND_MIRL_TOKEN_W05_ARGUMENT_COUNT_MISMATCH "[MIRL0025]"
#define ZEND_MIRL_TOKEN_W05_UNSUPPORTED_RESULT "[MIRL0026]"
#define ZEND_MIRL_TOKEN_W05_PROTECTED_CALL "[MIRL0027]"
#define ZEND_MIRL_TOKEN_W05_CALL_PLAN_FAILED "[MIRL0028]"
#define ZEND_MIRL_TOKEN_W05_CALL_VERIFY_FAILED "[MIRL0029]"

#endif /* ZEND_MIR_LOWERING_DIAGNOSTIC_H */
