/* Versioned process-local C runtime ABI for generated native code. */

#ifndef ZEND_NATIVE_RUNTIME_H
#define ZEND_NATIVE_RUNTIME_H

#include "Zend/Native/TPDE/Common/zend_tpde_backend.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ZEND_NATIVE_RUNTIME_ABI_VERSION 82u

typedef void (*zend_native_source_probe_t)(
	void *context,
	zend_execute_data *execute_data,
	uint32_t source_position_id);

typedef enum _zend_native_runtime_capability {
	ZEND_NATIVE_RUNTIME_CAP_USER_CALL = UINT64_C(1) << 0,
	ZEND_NATIVE_RUNTIME_CAP_INTERNAL_CALL = UINT64_C(1) << 1,
	ZEND_NATIVE_RUNTIME_CAP_ZVAL_SLOT = UINT64_C(1) << 2,
	ZEND_NATIVE_RUNTIME_CAP_OBSERVER = UINT64_C(1) << 3,
	ZEND_NATIVE_RUNTIME_CAP_INTERRUPT = UINT64_C(1) << 4,
	ZEND_NATIVE_RUNTIME_CAP_BAILOUT_BOUNDARY = UINT64_C(1) << 5,
	ZEND_NATIVE_RUNTIME_CAP_OBJECT_OPERATION = UINT64_C(1) << 6,
	ZEND_NATIVE_RUNTIME_CAP_DYNAMIC_BINDING = UINT64_C(1) << 7,
	ZEND_NATIVE_RUNTIME_CAP_SUSPEND = UINT64_C(1) << 8
} zend_native_runtime_capability;

typedef enum _zend_native_runtime_helper_id {
	ZEND_NATIVE_HELPER_USER_CALL_BEGIN = 1,
	ZEND_NATIVE_HELPER_USER_CALL_SET_INTEGER = 2,
	ZEND_NATIVE_HELPER_USER_CALL_SET_DOUBLE = 3,
	ZEND_NATIVE_HELPER_USER_CALL_FINISH = 4,
	ZEND_NATIVE_HELPER_ECHO_INTEGER = 5,
	ZEND_NATIVE_HELPER_ECHO_DOUBLE = 6,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_BEGIN = 7,
	ZEND_NATIVE_HELPER_CALL_SET_ZVAL = 8,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH = 9,
	ZEND_NATIVE_HELPER_INTERRUPT_POLL = 10,
	ZEND_NATIVE_HELPER_CALL_SET_SOURCE_ARGUMENT = 11,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH_SOURCE = 12,
	ZEND_NATIVE_HELPER_CALL_READ_SOURCE_SCALAR = 13,
	ZEND_NATIVE_HELPER_CATCH_ENTER = 14,
	ZEND_NATIVE_HELPER_USER_CALL_FINISH_SOURCE = 15,
	ZEND_NATIVE_HELPER_FINALLY_ENTER = 16,
	ZEND_NATIVE_HELPER_FINALLY_CALL = 17,
	ZEND_NATIVE_HELPER_FINALLY_RETURN = 18,
	ZEND_NATIVE_HELPER_RETURN_SOURCE_ZVAL = 19,
	ZEND_NATIVE_HELPER_VALUE_MAKE_REF = 20,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_REF = 21,
	ZEND_NATIVE_HELPER_VALUE_SEPARATE = 22,
	ZEND_NATIVE_HELPER_VALUE_COPY_TMP = 23,
	ZEND_NATIVE_HELPER_VALUE_FREE = 24,
	ZEND_NATIVE_HELPER_VALUE_UNSET_CV = 25,
	ZEND_NATIVE_HELPER_VALUE_CHECK_VAR = 26,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN = 27,
	ZEND_NATIVE_HELPER_VALUE_QM_ASSIGN = 28,
	ZEND_NATIVE_HELPER_VALUE_CONCAT = 29,
	ZEND_NATIVE_HELPER_VALUE_FAST_CONCAT = 30,
	ZEND_NATIVE_HELPER_VALUE_ROPE_INIT = 31,
	ZEND_NATIVE_HELPER_VALUE_ROPE_ADD = 32,
	ZEND_NATIVE_HELPER_VALUE_ROPE_END = 33,
	ZEND_NATIVE_HELPER_VALUE_INIT_ARRAY = 34,
	ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_ELEMENT = 35,
	ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_UNPACK = 36,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_R = 37,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_W = 38,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_RW = 39,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_IS = 40,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_FUNC_ARG = 41,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_UNSET = 42,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM = 43,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM_OP = 44,
	ZEND_NATIVE_HELPER_VALUE_UNSET_DIM = 45,
	ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_DIM = 46,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_OP = 47,
	ZEND_NATIVE_HELPER_VALUE_FE_FREE = 48,
	ZEND_NATIVE_HELPER_VALUE_ITERATOR_BRANCH = 49,
	ZEND_NATIVE_HELPER_VALUE_BINARY_OP = 50,
	ZEND_NATIVE_HELPER_VALUE_UNARY_OP = 51,
	ZEND_NATIVE_HELPER_VALUE_CAST = 52,
	ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_CV = 53,
	ZEND_NATIVE_HELPER_VALUE_FETCH_LIST = 54,
	ZEND_NATIVE_HELPER_VALUE_COND_BRANCH = 55,
	ZEND_NATIVE_HELPER_VALUE_INCDEC = 56,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_ANON_CLASS = 57,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_THIS = 58,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_R = 59,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_W = 60,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_RW = 61,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_IS = 62,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_FUNC_ARG = 63,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_UNSET = 64,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN = 65,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN_REF = 66,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN_OP = 67,
	ZEND_NATIVE_HELPER_OBJECT_UNSET = 68,
	ZEND_NATIVE_HELPER_OBJECT_ISSET_ISEMPTY = 69,
	ZEND_NATIVE_HELPER_OBJECT_PRE_INC = 70,
	ZEND_NATIVE_HELPER_OBJECT_PRE_DEC = 71,
	ZEND_NATIVE_HELPER_OBJECT_POST_INC = 72,
	ZEND_NATIVE_HELPER_OBJECT_POST_DEC = 73,
	ZEND_NATIVE_HELPER_OBJECT_INSTANCEOF = 74,
	ZEND_NATIVE_HELPER_OBJECT_CLONE = 75,
	ZEND_NATIVE_HELPER_STATIC_FETCH_R = 76,
	ZEND_NATIVE_HELPER_STATIC_FETCH_W = 77,
	ZEND_NATIVE_HELPER_STATIC_FETCH_RW = 78,
	ZEND_NATIVE_HELPER_STATIC_FETCH_IS = 79,
	ZEND_NATIVE_HELPER_STATIC_FETCH_FUNC_ARG = 80,
	ZEND_NATIVE_HELPER_STATIC_FETCH_UNSET = 81,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN = 82,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN_REF = 83,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN_OP = 84,
	ZEND_NATIVE_HELPER_STATIC_PRE_INC = 85,
	ZEND_NATIVE_HELPER_STATIC_PRE_DEC = 86,
	ZEND_NATIVE_HELPER_STATIC_POST_INC = 87,
	ZEND_NATIVE_HELPER_STATIC_POST_DEC = 88,
	ZEND_NATIVE_HELPER_STATIC_ISSET_ISEMPTY = 89,
	ZEND_NATIVE_HELPER_STATIC_UNSET = 90,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS = 91,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_CONSTANT = 92,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_LAMBDA = 93,
	ZEND_NATIVE_HELPER_OBJECT_BIND_LEXICAL = 94,
	ZEND_NATIVE_HELPER_OBJECT_BIND_STATIC = 95,
	ZEND_NATIVE_HELPER_THROW_SOURCE_ZVAL = 96,
	ZEND_NATIVE_HELPER_VALUE_TYPE_CHECK = 97,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_INTERNAL = 98,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_NAME = 99,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_FUNCTION = 100,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS = 101,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS_DELAYED = 102,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_R = 103,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_W = 104,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_RW = 105,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_IS = 106,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_FUNC_ARG = 107,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_UNSET = 108,
	ZEND_NATIVE_HELPER_DYNAMIC_UNSET_VAR = 109,
	ZEND_NATIVE_HELPER_DYNAMIC_ISSET_ISEMPTY_VAR = 110,
	ZEND_NATIVE_HELPER_DYNAMIC_BIND_GLOBAL = 111,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_GLOBALS = 112,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_CONSTANT = 113,
	ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_CONSTANT = 114,
	ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_ATTRIBUTED_CONSTANT = 115,
	ZEND_NATIVE_HELPER_DYNAMIC_INCLUDE_OR_EVAL = 116,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL = 117,
	ZEND_NATIVE_HELPER_VERIFY_RETURN_TYPE = 118,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL_ENTER = 119,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL_LEAVE = 120,
	ZEND_NATIVE_HELPER_VALUE_ECHO = 121,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL = 122,
	ZEND_NATIVE_HELPER_VALUE_FUNC_NUM_ARGS = 123,
	ZEND_NATIVE_HELPER_VALUE_FUNC_GET_ARGS = 124,
	ZEND_NATIVE_HELPER_ZVAL_STORE_INTEGER = 125,
	ZEND_NATIVE_HELPER_ZVAL_STORE_DOUBLE = 126,
	ZEND_NATIVE_HELPER_ZVAL_RELEASE_SLOW = 127,
	ZEND_NATIVE_HELPER_GENERATOR_CREATE = 128,
	ZEND_NATIVE_HELPER_GENERATOR_YIELD = 129,
	ZEND_NATIVE_HELPER_GENERATOR_YIELD_FROM = 130,
	ZEND_NATIVE_HELPER_GENERATOR_RETURN = 131,
	ZEND_NATIVE_HELPER_VALUE_COUNT = 132,
	ZEND_NATIVE_HELPER_VALUE_GET_TYPE = 133,
	ZEND_NATIVE_HELPER_VALUE_ARRAY_KEY_EXISTS = 134,
	ZEND_NATIVE_HELPER_VALUE_IN_ARRAY = 135,
	ZEND_NATIVE_HELPER_VALUE_ISSET_THIS = 136,
	ZEND_NATIVE_HELPER_VALUE_GET_CALLED_CLASS = 137,
	ZEND_NATIVE_HELPER_VALUE_BEGIN_SILENCE = 138,
	ZEND_NATIVE_HELPER_VALUE_END_SILENCE = 139,
	ZEND_NATIVE_HELPER_VALUE_MATCH_ERROR = 140,
	ZEND_NATIVE_HELPER_VALUE_VERIFY_NEVER_TYPE = 141,
	ZEND_NATIVE_HELPER_VALUE_DEFINED = 142,
	ZEND_NATIVE_HELPER_VALUE_TICKS = 143,
	ZEND_NATIVE_HELPER_VALUE_TYPE_ASSERT = 144,
	ZEND_NATIVE_HELPER_VALUE_EXT_STMT = 145,
	ZEND_NATIVE_HELPER_VALUE_EXT_FCALL_BEGIN = 146,
	ZEND_NATIVE_HELPER_VALUE_EXT_FCALL_END = 147,
	ZEND_NATIVE_HELPER_VALUE_EXT_NOP = 148,
	ZEND_NATIVE_HELPER_USER_OPCODE_INVOKE = 149,
	ZEND_NATIVE_HELPER_GENERATOR_USER_OPCODE_RETURN = 150,
	ZEND_NATIVE_HELPER_VALUE_DISCARD_EXCEPTION = 151,
	ZEND_NATIVE_HELPER_VALUE_CASE = 152,
	ZEND_NATIVE_HELPER_VALUE_BIND_STATIC_BRANCH = 153,
	ZEND_NATIVE_HELPER_VALUE_FRAMELESS_BRANCH = 154,
	ZEND_NATIVE_HELPER_USER_CALL_RESOLVE = 155,
	ZEND_NATIVE_HELPER_USER_CALL_RELEASE_RESOLUTION = 156,
	ZEND_NATIVE_HELPER_FINALLY_RETURN_EXPLICIT = 157,
	ZEND_NATIVE_HELPER_CATCH_EXPLICIT = 158,
	ZEND_NATIVE_HELPER_RECEIVE_EXPLICIT = 159,
	ZEND_NATIVE_HELPER_CALL_FRAGMENT = 160,
	ZEND_NATIVE_HELPER_CALL_FRAGMENT_EXPLICIT = 161,
	ZEND_NATIVE_HELPER_VALUE_CHECK_FUNC_ARG = 162,
	ZEND_NATIVE_HELPER_VALUE_CHECK_UNDEF_ARGS = 163,
	ZEND_NATIVE_HELPER_SOURCE_PROBE = 164,
	ZEND_NATIVE_HELPER_USER_CALL_NORMALIZE_RESOLUTION = 165,
	ZEND_NATIVE_HELPER_RECEIVE_EXPLICIT_PENDING = 166,
	ZEND_NATIVE_HELPER_CALL_CONVERT_EXPLICIT = 167,
	ZEND_NATIVE_HELPER_CALL_RESERVE_DYNAMIC_FRAME = 168,
	ZEND_NATIVE_HELPER_USER_CALL_EXPAND_ARGUMENTS = 169,
	ZEND_NATIVE_HELPER_FRAME_PREPARE = 170,
	ZEND_NATIVE_HELPER_FRAME_OBSERVER_BEGIN = 171,
	ZEND_NATIVE_HELPER_FRAME_OBSERVER_END = 172,
	ZEND_NATIVE_HELPER_FRAME_FINALIZE = 173,
	ZEND_NATIVE_HELPER_FRAME_ACTIVATION_RESERVE = 174,
	ZEND_NATIVE_HELPER_CHECK_FUNC_ARG_RESOLVED = 175,
	ZEND_NATIVE_HELPER_FRAME_ACTIVATION_POP = 176,
	/* Process-local generated-code ABI only; this is not a public PHP ABI. */
	ZEND_NATIVE_HELPER_FRAME_ACTIVATION_RELEASE = 177,
	ZEND_NATIVE_HELPER_CONST_INCLUDE_ONCE = 178,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL_SET_SOURCE_ARGUMENT = 179,
	ZEND_NATIVE_HELPER_USER_CALL_SEND_RESOLVED_ARGUMENT = 180,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL_SET_INTEGER_ARGUMENT = 181,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL_SET_DOUBLE_ARGUMENT = 182,
	ZEND_NATIVE_HELPER_PREPARE_FINALLY_EXCEPTION = 183,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_DIRECT = 184,
	ZEND_NATIVE_HELPER_VALUE_CONCAT_ASSIGN_DIRECT = 185,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_1 = 186,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_R_DIRECT = 187,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM_DIRECT = 188,
	ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_DIM_DIRECT = 189,
	ZEND_NATIVE_HELPER_USER_CALL_INVOKE = 190,
	ZEND_NATIVE_HELPER_CALL_FAST_LEAVE = 191,
	ZEND_NATIVE_HELPER_CALL_FAST_UNDEFINED_ARGUMENT = 192,
	ZEND_NATIVE_HELPER_CALL_FAST_PREPARE = 193,
	ZEND_NATIVE_HELPER_CALL_FAST_SCALAR_VIOLATION = 194,
	ZEND_NATIVE_HELPER_CALL_FAST_DYNAMIC_INIT = 195,
	ZEND_NATIVE_HELPER_CALL_FAST_SEND = 196,
	ZEND_NATIVE_HELPER_CALL_UNIVERSAL_INIT = 197,
	ZEND_NATIVE_HELPER_CALL_UNIVERSAL_DO = 198,
	ZEND_NATIVE_HELPER_CALL_UNIVERSAL_SEND = 199,
	ZEND_NATIVE_HELPER_CALL_FAST_NEW = 200,
	ZEND_NATIVE_HELPER_CALL_FAST_SEND_VAR_REFERENCE = 201,
	ZEND_NATIVE_HELPER_CALL_FAST_DO = 202,
	ZEND_NATIVE_HELPER_CALL_UNIVERSAL_EXPAND = 203,
	ZEND_NATIVE_HELPER_CALL_FAST_REARM = 204,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_PUSH = 205,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_DO_PLAIN = 206,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL_PLAIN = 207,
	ZEND_NATIVE_HELPER_VALUE_CONCAT_DIRECT = 208,
	ZEND_NATIVE_HELPER_VALUE_IDENTICAL_DIRECT = 209,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM_ADDRESS = 210,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_2_ADDRESS = 211,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_3_ADDRESS = 212,
	ZEND_NATIVE_HELPER_VALUE_INIT_ARRAY_ADDRESS = 213,
	ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_ELEMENT_ADDRESS = 214,
	ZEND_NATIVE_HELPER_CALL_FAST_RELEASE_CV = 215,
	/* Data, not a function: the one-character string zvals (string
	 * offset reads point at them). */
	ZEND_NATIVE_HELPER_CHAR_STRINGS = 216,
	ZEND_NATIVE_HELPER_COUNT = 217
} zend_native_runtime_helper_id;

/*
 * zend_native_call_frameless_direct() descriptor: handler index (bits 0-15),
 * argument count (16-17), CV arguments (18-20), temporary arguments (21-23),
 * literal arguments (24-26) and source position (32-63). Its slot words hold
 * the result offset and the first argument offset, then the second and third
 * argument offsets; a literal argument's offset indexes the literal table.
 */
#define ZEND_NATIVE_FRAMELESS_DIRECT_CV_SHIFT 18
#define ZEND_NATIVE_FRAMELESS_DIRECT_TMP_SHIFT 21
#define ZEND_NATIVE_FRAMELESS_DIRECT_CONST_SHIFT 24

/*
 * zend_native_value_fetch_dim_r_direct(), _assign_dim_direct() and
 * _isset_isempty_dim_direct() descriptor: key kind (bits 0-1), value kind
 * (2-3; the container kind, a CV or a temporary, for reads and isset/empty),
 * extended value (8-23) and source position (32-63). Their slot words hold
 * the container (a CV unless stated) and key offsets, then the value and
 * result offsets; a literal's offset indexes the literal table.
 */
/* _assign_dim_direct(): the container is a VAR holding an INDIRECT. */
#define ZEND_NATIVE_DIM_DIRECT_INDIRECT_CONTAINER_SHIFT 4
/* A read's result is a CV the optimizer named (no counted old value). */
#define ZEND_NATIVE_DIM_DIRECT_RESULT_CV_SHIFT 5
#define ZEND_NATIVE_DIM_DIRECT_UNUSED 0
#define ZEND_NATIVE_DIM_DIRECT_CONST 1
#define ZEND_NATIVE_DIM_DIRECT_CV 2
#define ZEND_NATIVE_DIM_DIRECT_TMP 3

/* zend_native_value_concat_assign_direct() value kinds. */
#define ZEND_NATIVE_CONCAT_DIRECT_CONST 0
#define ZEND_NATIVE_CONCAT_DIRECT_CV 1
#define ZEND_NATIVE_CONCAT_DIRECT_TMP 2

#define ZEND_NATIVE_RUNTIME_HELPER_WORD_COUNT \
	((ZEND_NATIVE_HELPER_COUNT + 63u) / 64u)

typedef enum _zend_native_iterator_branch_result {
	ZEND_NATIVE_ITERATOR_END = 0,
	ZEND_NATIVE_ITERATOR_NEXT = 1,
	ZEND_NATIVE_ITERATOR_EXCEPTION = 2
} zend_native_iterator_branch_result;

typedef enum _zend_native_catch_result {
	ZEND_NATIVE_CATCH_MATCHED = 0,
	/* Keep the exceptional status ABI-compatible with zend_native_status. */
	ZEND_NATIVE_CATCH_EXCEPTION = ZEND_NATIVE_EXCEPTION,
	ZEND_NATIVE_CATCH_BRANCH = 2
} zend_native_catch_result;

typedef enum _zend_native_runtime_effect {
	ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE = UINT32_C(1) << 0,
	ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT = UINT32_C(1) << 1,
	ZEND_NATIVE_RUNTIME_EFFECT_THROW = UINT32_C(1) << 2,
	ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT = UINT32_C(1) << 3,
	ZEND_NATIVE_RUNTIME_EFFECT_USERLAND = UINT32_C(1) << 4,
	ZEND_NATIVE_RUNTIME_EFFECT_REENTER = UINT32_C(1) << 5,
	ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE = UINT32_C(1) << 6,
	ZEND_NATIVE_RUNTIME_EFFECT_FRAME_READ = UINT32_C(1) << 7,
	ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE = UINT32_C(1) << 8,
	ZEND_NATIVE_RUNTIME_EFFECT_HEAP_READ = UINT32_C(1) << 9,
	ZEND_NATIVE_RUNTIME_EFFECT_HEAP_WRITE = UINT32_C(1) << 10,
	ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ = UINT32_C(1) << 11,
	ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_WRITE = UINT32_C(1) << 12,
	ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ = UINT32_C(1) << 13,
	ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE = UINT32_C(1) << 14,
	ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ = UINT32_C(1) << 15,
	ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_WRITE = UINT32_C(1) << 16,
	ZEND_NATIVE_RUNTIME_EFFECT_REFCOUNT = UINT32_C(1) << 17,
	ZEND_NATIVE_RUNTIME_EFFECT_INTERRUPT = UINT32_C(1) << 18
} zend_native_runtime_effect;

#define ZEND_NATIVE_RUNTIME_EFFECT_ALL ( \
	ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_RUNTIME_EFFECT_THROW \
	| ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT \
	| ZEND_NATIVE_RUNTIME_EFFECT_USERLAND \
	| ZEND_NATIVE_RUNTIME_EFFECT_REENTER \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE \
	| ZEND_NATIVE_RUNTIME_EFFECT_FRAME_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_REFCOUNT \
	| ZEND_NATIVE_RUNTIME_EFFECT_INTERRUPT)

typedef struct _zend_native_runtime_helper {
	uint32_t id;
	uint32_t effects;
	const void *address;
} zend_native_runtime_helper;

/*
 * The table is process-local and never serialized into MIR. Generated code
 * binds stable helper IDs to these addresses while it is compiled in the
 * current process. Helper ID N occupies table slot N - 1, so symbol binding is
 * constant-time and independent of registration order. Appending fields
 * requires a minor ABI version bump.
 */
typedef struct _zend_native_runtime_api {
	uint32_t abi_version;
	uint32_t struct_size;
	uint64_t capabilities;
	const zend_native_runtime_helper *helpers;
	uint32_t helper_count;
	uint32_t reserved;
} zend_native_runtime_api;

const zend_native_runtime_api *zend_native_runtime_get(void);
zend_result zend_native_runtime_validate(
	const zend_native_runtime_api *runtime,
	uint64_t required_capabilities,
	zend_native_diagnostic *diagnostic);
const zend_native_runtime_helper *zend_native_runtime_helper_find(
	const zend_native_runtime_api *runtime,
	zend_native_runtime_helper_id id);
void zend_native_runtime_set_source_probe(
	zend_native_source_probe_t probe, void *context);
bool zend_native_runtime_source_probe_enabled(void);
void zend_native_runtime_source_probe(uint32_t source_position_id);

#ifdef __cplusplus
}
#endif

#endif /* ZEND_NATIVE_RUNTIME_H */
