/* Versioned process-local C runtime ABI for generated native code. */

#ifndef ZEND_NATIVE_RUNTIME_H
#define ZEND_NATIVE_RUNTIME_H

#include "Zend/Native/TPDE/Common/zend_tpde_backend.h"

#ifdef __cplusplus
extern "C" {
#endif

#define ZEND_NATIVE_RUNTIME_ABI_VERSION 52u

typedef enum _zend_native_runtime_capability {
	ZEND_NATIVE_RUNTIME_CAP_USER_CALL = UINT64_C(1) << 0,
	ZEND_NATIVE_RUNTIME_CAP_INTERNAL_CALL = UINT64_C(1) << 1,
	ZEND_NATIVE_RUNTIME_CAP_ZVAL_SLOT = UINT64_C(1) << 2,
	ZEND_NATIVE_RUNTIME_CAP_OBSERVER = UINT64_C(1) << 3,
	ZEND_NATIVE_RUNTIME_CAP_INTERRUPT = UINT64_C(1) << 4,
	ZEND_NATIVE_RUNTIME_CAP_BAILOUT_BOUNDARY = UINT64_C(1) << 5,
	ZEND_NATIVE_RUNTIME_CAP_OBJECT_OPERATION = UINT64_C(1) << 6,
	ZEND_NATIVE_RUNTIME_CAP_DYNAMIC_BINDING = UINT64_C(1) << 7
} zend_native_runtime_capability;

typedef enum _zend_native_runtime_helper_id {
	ZEND_NATIVE_HELPER_USER_CALL_BEGIN = 1,
	ZEND_NATIVE_HELPER_USER_CALL_SET_INTEGER = 2,
	ZEND_NATIVE_HELPER_USER_CALL_SET_DOUBLE = 3,
	ZEND_NATIVE_HELPER_USER_CALL_FINISH = 4,
	ZEND_NATIVE_HELPER_ECHO_INTEGER = 5,
	ZEND_NATIVE_HELPER_ECHO_DOUBLE = 6,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_BEGIN = 7,
	ZEND_NATIVE_HELPER_CALL_SET_ZVAL = 8,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH = 9,
	ZEND_NATIVE_HELPER_INTERRUPT_POLL = 10,
	ZEND_NATIVE_HELPER_CALL_SET_SOURCE_ARGUMENT = 11,
	ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH_SOURCE = 12,
	ZEND_NATIVE_HELPER_CALL_READ_SOURCE_SCALAR = 13,
	ZEND_NATIVE_HELPER_CATCH_ENTER = 14,
	ZEND_NATIVE_HELPER_USER_CALL_FINISH_SOURCE = 15,
	ZEND_NATIVE_HELPER_FINALLY_ENTER = 16,
	ZEND_NATIVE_HELPER_FINALLY_CALL = 17,
	ZEND_NATIVE_HELPER_FINALLY_RETURN = 18,
	ZEND_NATIVE_HELPER_RETURN_SOURCE_ZVAL = 19,
	ZEND_NATIVE_HELPER_ABI_CONFORMANCE = 20,
	ZEND_NATIVE_HELPER_VALUE_MAKE_REF = 21,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_REF = 22,
	ZEND_NATIVE_HELPER_VALUE_SEPARATE = 23,
	ZEND_NATIVE_HELPER_VALUE_COPY_TMP = 24,
	ZEND_NATIVE_HELPER_VALUE_FREE = 25,
	ZEND_NATIVE_HELPER_VALUE_UNSET_CV = 26,
	ZEND_NATIVE_HELPER_VALUE_CHECK_VAR = 27,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN = 28,
	ZEND_NATIVE_HELPER_VALUE_QM_ASSIGN = 29,
	ZEND_NATIVE_HELPER_VALUE_CONCAT = 30,
	ZEND_NATIVE_HELPER_VALUE_FAST_CONCAT = 31,
	ZEND_NATIVE_HELPER_VALUE_ROPE_INIT = 32,
	ZEND_NATIVE_HELPER_VALUE_ROPE_ADD = 33,
	ZEND_NATIVE_HELPER_VALUE_ROPE_END = 34,
	ZEND_NATIVE_HELPER_VALUE_INIT_ARRAY = 35,
	ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_ELEMENT = 36,
	ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_UNPACK = 37,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_R = 38,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_W = 39,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_RW = 40,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_IS = 41,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_FUNC_ARG = 42,
	ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_UNSET = 43,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM = 44,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM_OP = 45,
	ZEND_NATIVE_HELPER_VALUE_UNSET_DIM = 46,
	ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_DIM = 47,
	ZEND_NATIVE_HELPER_VALUE_ASSIGN_OP = 48,
	ZEND_NATIVE_HELPER_VALUE_FE_FREE = 49,
	ZEND_NATIVE_HELPER_VALUE_ITERATOR_BRANCH = 50,
	ZEND_NATIVE_HELPER_VALUE_BINARY_OP = 51,
	ZEND_NATIVE_HELPER_VALUE_UNARY_OP = 52,
	ZEND_NATIVE_HELPER_VALUE_CAST = 53,
	ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_CV = 54,
	ZEND_NATIVE_HELPER_VALUE_FETCH_LIST = 55,
	ZEND_NATIVE_HELPER_VALUE_COND_BRANCH = 56,
	ZEND_NATIVE_HELPER_VALUE_INCDEC = 57,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_ANON_CLASS = 58,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_THIS = 59,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_R = 60,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_W = 61,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_RW = 62,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_IS = 63,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_FUNC_ARG = 64,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_UNSET = 65,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN = 66,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN_REF = 67,
	ZEND_NATIVE_HELPER_OBJECT_ASSIGN_OP = 68,
	ZEND_NATIVE_HELPER_OBJECT_UNSET = 69,
	ZEND_NATIVE_HELPER_OBJECT_ISSET_ISEMPTY = 70,
	ZEND_NATIVE_HELPER_OBJECT_PRE_INC = 71,
	ZEND_NATIVE_HELPER_OBJECT_PRE_DEC = 72,
	ZEND_NATIVE_HELPER_OBJECT_POST_INC = 73,
	ZEND_NATIVE_HELPER_OBJECT_POST_DEC = 74,
	ZEND_NATIVE_HELPER_OBJECT_INSTANCEOF = 75,
	ZEND_NATIVE_HELPER_OBJECT_CLONE = 76,
	ZEND_NATIVE_HELPER_STATIC_FETCH_R = 77,
	ZEND_NATIVE_HELPER_STATIC_FETCH_W = 78,
	ZEND_NATIVE_HELPER_STATIC_FETCH_RW = 79,
	ZEND_NATIVE_HELPER_STATIC_FETCH_IS = 80,
	ZEND_NATIVE_HELPER_STATIC_FETCH_FUNC_ARG = 81,
	ZEND_NATIVE_HELPER_STATIC_FETCH_UNSET = 82,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN = 83,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN_REF = 84,
	ZEND_NATIVE_HELPER_STATIC_ASSIGN_OP = 85,
	ZEND_NATIVE_HELPER_STATIC_PRE_INC = 86,
	ZEND_NATIVE_HELPER_STATIC_PRE_DEC = 87,
	ZEND_NATIVE_HELPER_STATIC_POST_INC = 88,
	ZEND_NATIVE_HELPER_STATIC_POST_DEC = 89,
	ZEND_NATIVE_HELPER_STATIC_ISSET_ISEMPTY = 90,
	ZEND_NATIVE_HELPER_STATIC_UNSET = 91,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS = 92,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_CONSTANT = 93,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_LAMBDA = 94,
	ZEND_NATIVE_HELPER_OBJECT_BIND_LEXICAL = 95,
	ZEND_NATIVE_HELPER_OBJECT_BIND_STATIC = 96,
	ZEND_NATIVE_HELPER_THROW_SOURCE_ZVAL = 97,
	ZEND_NATIVE_HELPER_VALUE_TYPE_CHECK = 98,
	ZEND_NATIVE_HELPER_CALL_FRAMELESS_INTERNAL = 99,
	ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_NAME = 100,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_FUNCTION = 101,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS = 102,
	ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS_DELAYED = 103,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_R = 104,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_W = 105,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_RW = 106,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_IS = 107,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_FUNC_ARG = 108,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_UNSET = 109,
	ZEND_NATIVE_HELPER_DYNAMIC_UNSET_VAR = 110,
	ZEND_NATIVE_HELPER_DYNAMIC_ISSET_ISEMPTY_VAR = 111,
	ZEND_NATIVE_HELPER_DYNAMIC_BIND_GLOBAL = 112,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_GLOBALS = 113,
	ZEND_NATIVE_HELPER_DYNAMIC_FETCH_CONSTANT = 114,
	ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_CONSTANT = 115,
	ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_ATTRIBUTED_CONSTANT = 116,
	ZEND_NATIVE_HELPER_DYNAMIC_INCLUDE_OR_EVAL = 117,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL = 118,
	ZEND_NATIVE_HELPER_VERIFY_RETURN_TYPE = 119,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL_ENTER = 120,
	ZEND_NATIVE_HELPER_DIRECT_USER_CALL_LEAVE = 121,
	ZEND_NATIVE_HELPER_VALUE_ECHO = 122,
	ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL = 123,
	ZEND_NATIVE_HELPER_VALUE_FUNC_NUM_ARGS = 124,
	ZEND_NATIVE_HELPER_VALUE_FUNC_GET_ARGS = 125,
	ZEND_NATIVE_HELPER_COUNT = 126
} zend_native_runtime_helper_id;

#define ZEND_NATIVE_RUNTIME_HELPER_WORD_COUNT \
	((ZEND_NATIVE_HELPER_COUNT + 63u) / 64u)

typedef enum _zend_native_iterator_branch_result {
	ZEND_NATIVE_ITERATOR_END = 0,
	ZEND_NATIVE_ITERATOR_NEXT = 1,
	ZEND_NATIVE_ITERATOR_EXCEPTION = 2
} zend_native_iterator_branch_result;

typedef enum _zend_native_runtime_effect {
	ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE = UINT32_C(1) << 0,
	ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT = UINT32_C(1) << 1,
	ZEND_NATIVE_RUNTIME_EFFECT_THROW = UINT32_C(1) << 2,
	ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT = UINT32_C(1) << 3,
	ZEND_NATIVE_RUNTIME_EFFECT_USERLAND = UINT32_C(1) << 4,
	ZEND_NATIVE_RUNTIME_EFFECT_REENTER = UINT32_C(1) << 5,
	ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE = UINT32_C(1) << 6,
	ZEND_NATIVE_RUNTIME_EFFECT_FRAME_READ = UINT32_C(1) << 7,
	ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE = UINT32_C(1) << 8,
	ZEND_NATIVE_RUNTIME_EFFECT_HEAP_READ = UINT32_C(1) << 9,
	ZEND_NATIVE_RUNTIME_EFFECT_HEAP_WRITE = UINT32_C(1) << 10,
	ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ = UINT32_C(1) << 11,
	ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_WRITE = UINT32_C(1) << 12,
	ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ = UINT32_C(1) << 13,
	ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE = UINT32_C(1) << 14,
	ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ = UINT32_C(1) << 15,
	ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_WRITE = UINT32_C(1) << 16,
	ZEND_NATIVE_RUNTIME_EFFECT_REFCOUNT = UINT32_C(1) << 17,
	ZEND_NATIVE_RUNTIME_EFFECT_INTERRUPT = UINT32_C(1) << 18
} zend_native_runtime_effect;

#define ZEND_NATIVE_RUNTIME_EFFECT_ALL ( \
	ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_RUNTIME_EFFECT_THROW \
	| ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT \
	| ZEND_NATIVE_RUNTIME_EFFECT_USERLAND \
	| ZEND_NATIVE_RUNTIME_EFFECT_REENTER \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE \
	| ZEND_NATIVE_RUNTIME_EFFECT_FRAME_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_REFCOUNT \
	| ZEND_NATIVE_RUNTIME_EFFECT_INTERRUPT)

typedef struct _zend_native_runtime_helper {
	uint32_t id;
	uint32_t effects;
	const void *address;
} zend_native_runtime_helper;

/*
 * The table is process-local and never serialized into MIR. Generated code
 * binds stable helper IDs to these addresses while it is compiled in the
 * current process. Helper ID N occupies table slot N - 1, so symbol binding is
 * constant-time and independent of registration order. Appending fields
 * requires a minor ABI version bump.
 */
typedef struct _zend_native_runtime_api {
	uint32_t abi_version;
	uint32_t struct_size;
	uint64_t capabilities;
	const zend_native_runtime_helper *helpers;
	uint32_t helper_count;
	uint32_t reserved;
} zend_native_runtime_api;

const zend_native_runtime_api *zend_native_runtime_get(void);
zend_result zend_native_runtime_validate(
	const zend_native_runtime_api *runtime,
	uint64_t required_capabilities,
	zend_native_diagnostic *diagnostic);
const zend_native_runtime_helper *zend_native_runtime_helper_find(
	const zend_native_runtime_api *runtime,
	zend_native_runtime_helper_id id);

#ifdef __cplusplus
}
#endif

#endif /* ZEND_NATIVE_RUNTIME_H */
