/* Process-local implementation of the native runtime ABI. */

#include "Zend/Native/Runtime/Common/zend_native_runtime.h"

#include "Zend/Native/Compiler/zend_native_dynamic_code.h"
#include "Zend/Native/Runtime/Common/zend_native_bindings.h"
#include "Zend/Native/Runtime/Common/zend_native_calls.h"
#include "Zend/Native/Runtime/Common/zend_native_objects.h"
#include "Zend/Native/Runtime/Common/zend_native_values.h"

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#define ZEND_NATIVE_EFFECT_FRAME_READ ( \
	ZEND_NATIVE_RUNTIME_EFFECT_FRAME_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_READ)
#define ZEND_NATIVE_EFFECT_FRAME_WRITE ( \
	ZEND_NATIVE_EFFECT_FRAME_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_HEAP_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_REFCOUNT)
#define ZEND_NATIVE_EFFECT_MAY_FAIL ( \
	ZEND_NATIVE_RUNTIME_EFFECT_THROW \
	| ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT)
#define ZEND_NATIVE_EFFECT_MAY_REENTER ( \
	ZEND_NATIVE_RUNTIME_EFFECT_USERLAND \
	| ZEND_NATIVE_RUNTIME_EFFECT_REENTER \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE)
#define ZEND_NATIVE_EFFECT_CALL ( \
	ZEND_NATIVE_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_ARRAY_READ ( \
	ZEND_NATIVE_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ)
#define ZEND_NATIVE_EFFECT_ARRAY_WRITE ( \
	ZEND_NATIVE_EFFECT_ARRAY_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_WRITE)
#define ZEND_NATIVE_EFFECT_ARRAY_SLOW_READ ( \
	ZEND_NATIVE_EFFECT_ARRAY_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE ( \
	ZEND_NATIVE_EFFECT_ARRAY_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_OBJECT_READ ( \
	ZEND_NATIVE_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ)
#define ZEND_NATIVE_EFFECT_OBJECT_WRITE ( \
	ZEND_NATIVE_EFFECT_OBJECT_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE)
#define ZEND_NATIVE_EFFECT_OBJECT_SLOW_READ ( \
	ZEND_NATIVE_EFFECT_OBJECT_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE ( \
	ZEND_NATIVE_EFFECT_OBJECT_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_SYMBOL_READ ( \
	ZEND_NATIVE_EFFECT_FRAME_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ)
#define ZEND_NATIVE_EFFECT_SYMBOL_WRITE ( \
	ZEND_NATIVE_EFFECT_SYMBOL_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_WRITE)
#define ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ ( \
	ZEND_NATIVE_EFFECT_SYMBOL_READ \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)
#define ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE ( \
	ZEND_NATIVE_EFFECT_SYMBOL_WRITE \
	| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE \
	| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT \
	| ZEND_NATIVE_EFFECT_MAY_FAIL \
	| ZEND_NATIVE_EFFECT_MAY_REENTER)

static const zend_native_runtime_helper zend_native_runtime_helpers[] = {
	{ZEND_NATIVE_HELPER_USER_CALL_BEGIN,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_call_begin},
	{ZEND_NATIVE_HELPER_USER_CALL_SET_INTEGER,
		ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE,
		(const void *) zend_native_call_set_integer_argument},
	{ZEND_NATIVE_HELPER_USER_CALL_SET_DOUBLE,
		ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE,
		(const void *) zend_native_call_set_double_argument},
	{ZEND_NATIVE_HELPER_USER_CALL_FINISH, ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_invoke_finish},
	{ZEND_NATIVE_HELPER_ECHO_INTEGER,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE,
		(const void *) zend_native_echo_integer},
	{ZEND_NATIVE_HELPER_ECHO_DOUBLE,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE,
		(const void *) zend_native_echo_double},
	{ZEND_NATIVE_HELPER_INTERNAL_CALL_BEGIN,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_internal_call_begin},
	{ZEND_NATIVE_HELPER_CALL_SET_ZVAL,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE,
		(const void *) zend_native_call_set_zval_argument},
	{ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH, ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_internal_call_invoke_finish},
	{ZEND_NATIVE_HELPER_INTERRUPT_POLL,
		ZEND_NATIVE_RUNTIME_EFFECT_THROW | ZEND_NATIVE_RUNTIME_EFFECT_BAILOUT
			| ZEND_NATIVE_RUNTIME_EFFECT_USERLAND
			| ZEND_NATIVE_RUNTIME_EFFECT_REENTER
			| ZEND_NATIVE_RUNTIME_EFFECT_INTERRUPT,
		(const void *) zend_native_interrupt_poll},
	{ZEND_NATIVE_HELPER_CALL_SET_SOURCE_ARGUMENT,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_call_set_source_argument},
	{ZEND_NATIVE_HELPER_INTERNAL_CALL_FINISH_SOURCE,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_internal_call_invoke_finish_source},
	{ZEND_NATIVE_HELPER_CALL_READ_SOURCE_SCALAR,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_call_read_source_scalar},
	{ZEND_NATIVE_HELPER_CATCH_ENTER,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_RUNTIME_EFFECT_THROW,
		(const void *) zend_native_catch_enter},
	{ZEND_NATIVE_HELPER_USER_CALL_FINISH_SOURCE,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_invoke_finish_source},
	{ZEND_NATIVE_HELPER_FINALLY_ENTER,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_THROW,
		(const void *) zend_native_finally_enter},
	{ZEND_NATIVE_HELPER_FINALLY_CALL, ZEND_NATIVE_RUNTIME_EFFECT_FRAME_WRITE,
		(const void *) zend_native_finally_call},
	{ZEND_NATIVE_HELPER_FINALLY_RETURN,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_THROW,
		(const void *) zend_native_finally_return},
	{ZEND_NATIVE_HELPER_RETURN_SOURCE_ZVAL,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_RUNTIME_EFFECT_THROW,
		(const void *) zend_native_return_source_zval},
	{ZEND_NATIVE_HELPER_ABI_CONFORMANCE, 0,
		(const void *) zend_native_abi_conformance},
	{ZEND_NATIVE_HELPER_VALUE_MAKE_REF,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE,
		(const void *) zend_native_value_make_ref},
	{ZEND_NATIVE_HELPER_VALUE_ASSIGN_REF,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_assign_ref},
	{ZEND_NATIVE_HELPER_VALUE_SEPARATE,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE,
		(const void *) zend_native_value_separate},
	{ZEND_NATIVE_HELPER_VALUE_COPY_TMP,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE,
		(const void *) zend_native_value_copy_tmp},
	{ZEND_NATIVE_HELPER_VALUE_FREE,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_free},
	{ZEND_NATIVE_HELPER_VALUE_UNSET_CV,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_unset_cv},
	{ZEND_NATIVE_HELPER_VALUE_CHECK_VAR,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_check_var},
	{ZEND_NATIVE_HELPER_VALUE_ASSIGN,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_assign},
	{ZEND_NATIVE_HELPER_VALUE_QM_ASSIGN,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_qm_assign},
	{ZEND_NATIVE_HELPER_VALUE_CONCAT,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_concat},
	{ZEND_NATIVE_HELPER_VALUE_FAST_CONCAT,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_fast_concat},
	{ZEND_NATIVE_HELPER_VALUE_ROPE_INIT,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_rope_init},
	{ZEND_NATIVE_HELPER_VALUE_ROPE_ADD,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_rope_add},
	{ZEND_NATIVE_HELPER_VALUE_ROPE_END,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_rope_end},
	{ZEND_NATIVE_HELPER_VALUE_INIT_ARRAY,
		ZEND_NATIVE_EFFECT_ARRAY_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_init_array},
	{ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_ELEMENT,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_add_array_element},
	{ZEND_NATIVE_HELPER_VALUE_ADD_ARRAY_UNPACK,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_add_array_unpack},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_R, ZEND_NATIVE_EFFECT_ARRAY_SLOW_READ,
		(const void *) zend_native_value_fetch_dim_r},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_W, ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_fetch_dim_w},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_RW, ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_fetch_dim_rw},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_IS, ZEND_NATIVE_EFFECT_ARRAY_SLOW_READ,
		(const void *) zend_native_value_fetch_dim_is},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_FUNC_ARG,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_fetch_dim_func_arg},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_DIM_UNSET,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_fetch_dim_unset},
	{ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM, ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_assign_dim},
	{ZEND_NATIVE_HELPER_VALUE_ASSIGN_DIM_OP,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_assign_dim_op},
	{ZEND_NATIVE_HELPER_VALUE_UNSET_DIM, ZEND_NATIVE_EFFECT_ARRAY_SLOW_WRITE,
		(const void *) zend_native_value_unset_dim},
	{ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_DIM,
		ZEND_NATIVE_EFFECT_ARRAY_SLOW_READ,
		(const void *) zend_native_value_isset_isempty_dim},
	{ZEND_NATIVE_HELPER_VALUE_ASSIGN_OP,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_assign_op},
	{ZEND_NATIVE_HELPER_VALUE_FE_FREE,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_fe_free},
	{ZEND_NATIVE_HELPER_VALUE_ITERATOR_BRANCH,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ARRAY_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_iterator_branch},
	{ZEND_NATIVE_HELPER_VALUE_BINARY_OP,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_binary_op},
	{ZEND_NATIVE_HELPER_VALUE_UNARY_OP,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_unary_op},
	{ZEND_NATIVE_HELPER_VALUE_CAST,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_cast},
	{ZEND_NATIVE_HELPER_VALUE_ISSET_ISEMPTY_CV,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_RUNTIME_EFFECT_OBSERVE,
		(const void *) zend_native_value_isset_isempty_cv},
	{ZEND_NATIVE_HELPER_VALUE_FETCH_LIST, ZEND_NATIVE_EFFECT_ARRAY_SLOW_READ,
		(const void *) zend_native_value_fetch_list},
	{ZEND_NATIVE_HELPER_VALUE_COND_BRANCH,
		ZEND_NATIVE_EFFECT_FRAME_READ | ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_value_cond_branch},
	{ZEND_NATIVE_HELPER_VALUE_INCDEC,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_incdec},
	{ZEND_NATIVE_HELPER_OBJECT_DECLARE_ANON_CLASS,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_object_declare_anon_class},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_THIS, ZEND_NATIVE_EFFECT_OBJECT_READ,
		(const void *) zend_native_execute_object_fetch_this},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_R, ZEND_NATIVE_EFFECT_OBJECT_SLOW_READ,
		(const void *) zend_native_execute_object_fetch_r},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_W, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_fetch_w},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_RW, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_fetch_rw},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_IS, ZEND_NATIVE_EFFECT_OBJECT_SLOW_READ,
		(const void *) zend_native_execute_object_fetch_is},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_FUNC_ARG,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_fetch_func_arg},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_UNSET,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_fetch_unset},
	{ZEND_NATIVE_HELPER_OBJECT_ASSIGN, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_assign},
	{ZEND_NATIVE_HELPER_OBJECT_ASSIGN_REF,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_assign_ref},
	{ZEND_NATIVE_HELPER_OBJECT_ASSIGN_OP,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_assign_op},
	{ZEND_NATIVE_HELPER_OBJECT_UNSET, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_unset},
	{ZEND_NATIVE_HELPER_OBJECT_ISSET_ISEMPTY,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_READ,
		(const void *) zend_native_execute_object_isset_isempty},
	{ZEND_NATIVE_HELPER_OBJECT_PRE_INC, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_pre_inc},
	{ZEND_NATIVE_HELPER_OBJECT_PRE_DEC, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_pre_dec},
	{ZEND_NATIVE_HELPER_OBJECT_POST_INC, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_post_inc},
	{ZEND_NATIVE_HELPER_OBJECT_POST_DEC, ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_post_dec},
	{ZEND_NATIVE_HELPER_OBJECT_INSTANCEOF,
		ZEND_NATIVE_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_execute_object_instanceof},
	{ZEND_NATIVE_HELPER_OBJECT_CLONE,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_clone},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_R,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ,
		(const void *) zend_native_execute_static_fetch_r},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_W,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_fetch_w},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_RW,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_fetch_rw},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_IS,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ,
		(const void *) zend_native_execute_static_fetch_is},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_FUNC_ARG,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_fetch_func_arg},
	{ZEND_NATIVE_HELPER_STATIC_FETCH_UNSET,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_fetch_unset},
	{ZEND_NATIVE_HELPER_STATIC_ASSIGN,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_assign},
	{ZEND_NATIVE_HELPER_STATIC_ASSIGN_REF,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_assign_ref},
	{ZEND_NATIVE_HELPER_STATIC_ASSIGN_OP,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_assign_op},
	{ZEND_NATIVE_HELPER_STATIC_PRE_INC,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_pre_inc},
	{ZEND_NATIVE_HELPER_STATIC_PRE_DEC,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_pre_dec},
	{ZEND_NATIVE_HELPER_STATIC_POST_INC,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_post_inc},
	{ZEND_NATIVE_HELPER_STATIC_POST_DEC,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_post_dec},
	{ZEND_NATIVE_HELPER_STATIC_ISSET_ISEMPTY,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ,
		(const void *) zend_native_execute_static_isset_isempty},
	{ZEND_NATIVE_HELPER_STATIC_UNSET,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_static_unset},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS,
		ZEND_NATIVE_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_execute_object_fetch_class},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_CONSTANT,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ,
		(const void *) zend_native_execute_object_fetch_class_constant},
	{ZEND_NATIVE_HELPER_OBJECT_DECLARE_LAMBDA,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ,
		(const void *) zend_native_execute_object_declare_lambda},
	{ZEND_NATIVE_HELPER_OBJECT_BIND_LEXICAL,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_bind_lexical},
	{ZEND_NATIVE_HELPER_OBJECT_BIND_STATIC,
		ZEND_NATIVE_EFFECT_OBJECT_SLOW_WRITE,
		(const void *) zend_native_execute_object_bind_static},
	{ZEND_NATIVE_HELPER_THROW_SOURCE_ZVAL,
		ZEND_NATIVE_EFFECT_FRAME_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_RUNTIME_EFFECT_THROW,
		(const void *) zend_native_throw_source_zval},
	{ZEND_NATIVE_HELPER_VALUE_TYPE_CHECK,
		ZEND_NATIVE_EFFECT_FRAME_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_type_check},
	{ZEND_NATIVE_HELPER_CALL_FRAMELESS_INTERNAL,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_frameless_internal},
	{ZEND_NATIVE_HELPER_OBJECT_FETCH_CLASS_NAME,
		ZEND_NATIVE_EFFECT_OBJECT_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_SYMBOL_TABLE_READ
			| ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_EFFECT_MAY_FAIL,
		(const void *) zend_native_execute_object_fetch_class_name},
	{ZEND_NATIVE_HELPER_OBJECT_DECLARE_FUNCTION,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_execute_object_declare_function},
	{ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_object_declare_class},
	{ZEND_NATIVE_HELPER_OBJECT_DECLARE_CLASS_DELAYED,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_object_declare_class_delayed},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_R, ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ,
		(const void *) zend_native_dynamic_fetch_r},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_W, ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_fetch_w},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_RW, ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_fetch_rw},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_IS, ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ,
		(const void *) zend_native_dynamic_fetch_is},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_FUNC_ARG,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_fetch_func_arg},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_UNSET,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_fetch_unset},
	{ZEND_NATIVE_HELPER_DYNAMIC_UNSET_VAR,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_unset_var},
	{ZEND_NATIVE_HELPER_DYNAMIC_ISSET_ISEMPTY_VAR,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ,
		(const void *) zend_native_dynamic_isset_isempty_var},
	{ZEND_NATIVE_HELPER_DYNAMIC_BIND_GLOBAL,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_bind_global},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_GLOBALS,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ,
		(const void *) zend_native_dynamic_fetch_globals},
	{ZEND_NATIVE_HELPER_DYNAMIC_FETCH_CONSTANT,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_READ,
		(const void *) zend_native_dynamic_fetch_constant},
	{ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_CONSTANT,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_declare_constant},
	{ZEND_NATIVE_HELPER_DYNAMIC_DECLARE_ATTRIBUTED_CONSTANT,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE,
		(const void *) zend_native_dynamic_declare_attributed_constant},
	{ZEND_NATIVE_HELPER_DYNAMIC_INCLUDE_OR_EVAL,
		ZEND_NATIVE_EFFECT_SYMBOL_SLOW_WRITE
			| ZEND_NATIVE_RUNTIME_EFFECT_OBJECT_WRITE,
		(const void *) zend_native_execute_include_or_eval},
	{ZEND_NATIVE_HELPER_DIRECT_USER_CALL,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_direct},
	{ZEND_NATIVE_HELPER_VERIFY_RETURN_TYPE,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_RUNTIME_EFFECT_THROW
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_verify_return_type},
	{ZEND_NATIVE_HELPER_DIRECT_USER_CALL_ENTER,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_direct_enter},
	{ZEND_NATIVE_HELPER_DIRECT_USER_CALL_LEAVE,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_call_direct_leave},
	{ZEND_NATIVE_HELPER_VALUE_ECHO,
		ZEND_NATIVE_EFFECT_FRAME_WRITE | ZEND_NATIVE_RUNTIME_EFFECT_ALLOCATE
			| ZEND_NATIVE_RUNTIME_EFFECT_DESTRUCT
			| ZEND_NATIVE_EFFECT_MAY_FAIL
			| ZEND_NATIVE_EFFECT_MAY_REENTER,
		(const void *) zend_native_value_echo},
	{ZEND_NATIVE_HELPER_DIRECT_INTERNAL_CALL,
		ZEND_NATIVE_EFFECT_CALL,
		(const void *) zend_native_internal_call_direct},
};

static const zend_native_runtime_api zend_native_runtime = {
	ZEND_NATIVE_RUNTIME_ABI_VERSION,
	sizeof(zend_native_runtime_api),
	ZEND_NATIVE_RUNTIME_CAP_USER_CALL
		| ZEND_NATIVE_RUNTIME_CAP_INTERNAL_CALL
		| ZEND_NATIVE_RUNTIME_CAP_ZVAL_SLOT
		| ZEND_NATIVE_RUNTIME_CAP_OBSERVER
		| ZEND_NATIVE_RUNTIME_CAP_INTERRUPT
		| ZEND_NATIVE_RUNTIME_CAP_BAILOUT_BOUNDARY
		| ZEND_NATIVE_RUNTIME_CAP_OBJECT_OPERATION
		| ZEND_NATIVE_RUNTIME_CAP_DYNAMIC_BINDING,
	zend_native_runtime_helpers,
	(uint32_t) (sizeof(zend_native_runtime_helpers)
		/ sizeof(zend_native_runtime_helpers[0])),
	0
};

static void zend_native_runtime_diagnostic(
	zend_native_diagnostic *diagnostic,
	zend_native_diagnostic_code code,
	const char *message)
{
	if (diagnostic == NULL) {
		return;
	}
	diagnostic->code = code;
	snprintf(diagnostic->message, sizeof(diagnostic->message), "%s", message);
}

const zend_native_runtime_api *zend_native_runtime_get(void)
{
	return &zend_native_runtime;
}

const zend_native_runtime_helper *zend_native_runtime_helper_find(
	const zend_native_runtime_api *runtime,
	zend_native_runtime_helper_id id)
{
	uint32_t index;

	if (runtime == NULL || runtime->helpers == NULL) {
		return NULL;
	}
	for (index = 0; index < runtime->helper_count; index++) {
		if (runtime->helpers[index].id == (uint32_t) id) {
			return &runtime->helpers[index];
		}
	}
	return NULL;
}

zend_result zend_native_runtime_validate(
	const zend_native_runtime_api *runtime,
	uint64_t required_capabilities,
	zend_native_diagnostic *diagnostic)
{
	uint32_t index;
	uint64_t seen[ZEND_NATIVE_RUNTIME_HELPER_WORD_COUNT] = {0};

	if (runtime == NULL
			|| runtime->abi_version != ZEND_NATIVE_RUNTIME_ABI_VERSION
			|| runtime->struct_size < sizeof(zend_native_runtime_api)
			|| runtime->helpers == NULL || runtime->helper_count == 0) {
		zend_native_runtime_diagnostic(diagnostic,
			ZEND_NATIVE_DIAGNOSTIC_INVALID_ARGUMENT,
			"native runtime ABI version or size is incompatible");
		return FAILURE;
	}
	if ((runtime->capabilities & required_capabilities)
			!= required_capabilities) {
		zend_native_runtime_diagnostic(diagnostic,
			ZEND_NATIVE_DIAGNOSTIC_UNSUPPORTED_OPCODE,
			"native runtime lacks a required capability");
		return FAILURE;
	}
	for (index = 0; index < runtime->helper_count; index++) {
		const zend_native_runtime_helper *helper = &runtime->helpers[index];

		if (helper->id == 0 || helper->id >= ZEND_NATIVE_HELPER_COUNT
				|| helper->address == NULL
				|| (helper->effects & ~ZEND_NATIVE_RUNTIME_EFFECT_ALL) != 0
				|| ((helper->effects & ZEND_NATIVE_RUNTIME_EFFECT_REENTER) != 0
					&& (helper->effects
						& ZEND_NATIVE_RUNTIME_EFFECT_USERLAND) == 0)
				|| (seen[helper->id / 64u]
					& (UINT64_C(1) << (helper->id % 64u))) != 0) {
			zend_native_runtime_diagnostic(diagnostic,
				ZEND_NATIVE_DIAGNOSTIC_INVALID_ARGUMENT,
				"native runtime helper contract is invalid or contradictory");
			return FAILURE;
		}
		seen[helper->id / 64u] |= UINT64_C(1) << (helper->id % 64u);
	}
	return SUCCESS;
}
