/* Source-backed object operations for generated native code. */

#ifndef ZEND_NATIVE_OBJECTS_H
#define ZEND_NATIVE_OBJECTS_H

#include "Zend/Native/Runtime/Common/zend_native_runtime.h"

#ifdef __cplusplus
extern "C" {
#endif

zend_native_status zend_native_execute_object_fetch_r(
	zend_execute_data *execute_data,
	uint64_t op1, uint64_t op2, uint64_t result,
	uint32_t extended_value, uint32_t source_opcode,
	uint32_t source_position_id);
#define ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(name) \
	zend_native_status name( \
		zend_execute_data *execute_data, \
		uint64_t op1, uint64_t op2, uint64_t result, \
		uint32_t extended_value, uint32_t source_opcode, \
		uint32_t source_position_id);
ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(
	zend_native_execute_object_fetch_w)
ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(
	zend_native_execute_object_fetch_rw)
ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(
	zend_native_execute_object_fetch_is)
ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(
	zend_native_execute_object_fetch_func_arg)
ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER(
	zend_native_execute_object_fetch_unset)
#undef ZEND_NATIVE_EXPLICIT_OBJECT_FETCH_HELPER

#define ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(name) \
	zend_native_status name( \
		zend_execute_data *execute_data, \
		uint64_t op1, uint64_t op2, uint64_t result, \
		uint32_t extended_value, uint32_t source_opcode, \
		uint32_t source_position_id);
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_declare_anon_class)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_fetch_this)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_unset)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_isset_isempty)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_pre_inc)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_pre_dec)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_post_inc)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_post_dec)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_instanceof)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_clone)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_object_fetch_class)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_fetch_class_constant)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_fetch_class_name)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_declare_lambda)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_bind_lexical)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_bind_static)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_declare_function)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_declare_class)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_object_declare_class_delayed)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_fetch_r)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_fetch_w)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_fetch_rw)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_fetch_is)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_static_fetch_func_arg)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_fetch_unset)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_pre_inc)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_pre_dec)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_post_inc)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_post_dec)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(
	zend_native_execute_static_isset_isempty)
ZEND_NATIVE_EXPLICIT_OBJECT_HELPER(zend_native_execute_static_unset)
#undef ZEND_NATIVE_EXPLICIT_OBJECT_HELPER

#define ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(name) \
	zend_native_status name( \
		zend_execute_data *execute_data, \
		uint64_t op1, uint64_t op2, uint64_t result, uint64_t auxiliary, \
		uint32_t extended_value, uint32_t source_opcode, \
		uint32_t source_position_id);
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_object_assign)
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_object_assign_ref)
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_object_assign_op)
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_static_assign)
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_static_assign_ref)
ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER(
	zend_native_execute_static_assign_op)
#undef ZEND_NATIVE_EXPLICIT_OBJECT_ASSIGNMENT_HELPER

zend_native_status zend_native_throw_source_zval(
	zend_execute_data *execute_data, uint64_t operand,
	uint32_t source_opcode, uint32_t source_position_id);

#ifdef __cplusplus
}
#endif

#endif /* ZEND_NATIVE_OBJECTS_H */
